### ISSUE TITLE
how can i install dolt base on alpine image? failed...

### ISSUE THREAD

**Issue by med1tator** [dolthub/dolt#1489]
here is my dockerfile:
```dockerfile
FROM alpine

RUN apk add --no-cache bash
USER root
RUN curl -L https://github.com/dolthub/dolt/releases/latest/download/install.sh | bash
```
but this image just cant use dolt :
```bash
bash-5.1# ls /usr/local/bin/
dolt             git-dolt         git-dolt-smudge
bash-5.1# dolt 
bash: /usr/local/bin/dolt: No such file or directory
bash-5.1# 
```
![image](https://user-images.githubusercontent.com/33922888/112733468-38b3f800-8f7b-11eb-8018-56804b757757.png)

**Comment by VinaiRachakonda** [comment]
@med1tator This should work so I'm sorry you're having problems. I'll take a look at this ASAP

**Comment by max-hoffman** [comment]
Try adding curl to your apk install?
```bash
Step 4/4 : RUN curl -L https://github.com/dolthub/dolt/releases/latest/download/install.sh | bash
 ---> Running in 60378f493916
/bin/sh: curl: not found
```

**Comment by max-hoffman** [comment]
@med1tator When I install curl + bash that fixes this for me:
```Dockerfile
FROM alpine

RUN apk add --no-cache bash curl
USER root
RUN curl -L https://github.com/dolthub/dolt/releases/latest/download/install.sh | bash
```

**Comment by reltuk** [comment]
This currently happens because our dolt releases for linux-amd64 are ELF binaries linked against glibc. The following `Dockerfile` is a way to use an alpine image with glibc installed to get dolt running:

```dockerfile
FROM frolvlad/alpine-glibc:latest

RUN apk add --no-cache bash curl
USER root
RUN curl -L https://github.com/dolthub/dolt/releases/latest/download/install.sh | bash
```

We're going to look into

1) Making `install.sh` fail when glibc is not available on linux-amd64.
2) If we can build statically linked releases, or releases specific to musl libc...something that would allow `install.sh` to work on alpine out of the box.

**Comment by med1tator** [comment]
> ```dockerfile
> frolvlad
> ```

Worked, thanks and i found other way to solved this.
```dockerfile
FROM alpine

RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
RUN curl -L https://github.com/dolthub/dolt/releases/latest/download/install.sh | bash
```
