### ISSUE TITLE
DELIMITER command does not work with non-interactive stdin

### ISSUE THREAD

**Issue by cipharius** [dolthub/dolt#1495]
Was trying to create reproduction example for other issue regarding stored procedures, but I could not use the `DELIMITER` command, in order to define multi-statement stored procedure.

Example:
```mysql
DELIMITER //

CREATE PROCEDURE test()
BEGIN
  SET msg = 'Test example';
  SELECT @msg;
END//

DELIMITER ;
```

Defining this line by line via interactive `dolt sql` session works (although when using delimiter command, you must enter the old delimiter right after calling the `DELIMITER` command).
But when called non-interactively (`dolt sql < example.sql`), dolt complains about delimiter command.

As far as I am aware, there is no other alternative to define multi-statement procedure, without temporarely changing the delimiter, right?

**Comment by Hydrocharged** [comment]
To define procedures, you can also use the `--query` flag, like so:
```
dolt sql -q "CREATE PROCEDURE test() BEGIN SET msg = 'Test example'; SELECT @msg; END"
```
For the example that you gave, right now we only support the `DELIMITER` command when followed with the old delimiter, as you pointed out using the interactive session. Running your above script as `dolt sql < example.sql` and adding the previous delimiter to each call allows the file to process as expected.

I'll look into adding support for newline termination rather than only previous delimiter termination for `DELIMITER` calls.

**Comment by Hydrocharged** [comment]
@cipharius This is fixed in the above PR!
