### ISSUE TITLE
Replication and clustering

### ISSUE THREAD

**Issue by drequivalent** [dolthub/dolt#1602]
What solutions does Dolt provide in terms of replicating data between the servers and creating high-availability clusters?

I have a project in my sights that would make an extensive use for this exact kind of database, which would help us find and eliminate a lot of problems with data drift that started popping up lately, and we'd like to continue using this type of database version control in the future - in which a high-availability mirroring cluster for the database is planned.

So, are there any internal or external solutions for this type of work?

**Comment by timsehn** [comment]
We'd be happy to hop on a call with you to explain our model.

Here's what we've documented: https://docs.dolthub.com/reference/characteristics

We support push, pull, and fetch in the git style to do replication. So right now, replication is user driven. We want to build replication (even to potentially to MySQL as a read replica) but we need someone (likely a paying customer) to want it for it to pop to the top of our priority list.

**Comment by drequivalent** [comment]
So how do I use this multi-instance setup?

And what kind of paying customer do you need? 

I think the good idea will be for Dolt server (or a galera-like mirrored cluster) to handle all the writes (which can be slow - but they'll), and the MySQL/galera read cluster to handle all the reads.

**Comment by timsehn** [comment]
How do you do this now? It really depends on what you want to do. There's no cookie cutter answer.

Dolt replicating to MySQL for reads is definitely on our roadmap. 

We sell enterprise support contracts starting at $2K/month. I think it would take interest at that level or higher for us to reshuffle our priorities and start building this now. If that's you, you can email me at tim@dolthub.com. We'll jkeep this ticket updated otherwise.

**Comment by zachmu** [comment]
We're beginning to work on replication this month, stay tuned.

**Comment by timsehn** [comment]
Replication is implemented.

https://docs.dolthub.com/sql-reference/server/replication
