### ISSUE TITLE
Foreign key violation error when inserting NULLs to foreign key columns

### ISSUE THREAD

**Issue by katiemcculloch** [dolthub/dolt#1775]
There are 2 paths where we've seen this error come up:
1) dolt table import -u <tableName> <file_name.csv> where the CSV has "blanks" for NULL values
2) `dolt commit` in sql-server. It seems like there is an extra foreign key check on `dolt commit` that is not working.

i.e.:
```
UPDATE datasets SET format_types_id = 10 where id = '3ae6ddf7cf734e359b1ebfe244e9997f';
cannot add or update a child row - Foreign key violation on fk: `datasets_format_types_fk`, table: `datasets`, referenced table: `format_types`, key: `(12633,10)`
```

**Comment by Hydrocharged** [comment]
These are two different issues. Using `dolt table import`, blanks are treated as empty strings, where as foreign keys require `NULL` values. We might want to add an option to interpret blanks as `NULL`s?

I can't reproduce the 2nd issue. From what was posted in internal chat, I've been unable to find where the issue is or observe any incorrect behavior. When this happens again, we should get the exact repro steps so I can troubleshoot it.
