### ISSUE TITLE
Schema changes for `dolt_diff_$tablename` and `dolt_commit_diff_$tablename`

### ISSUE THREAD

**Issue by andrew-wm-arthur** [dolthub/dolt#1910]
Currently both diff tables create a composite schema that is the union of all super schemas on all branches (super duper schema 😉 ). The rationale for this is to be able to render any value found in any commit that the diff tables may encounter while traversing the history. However, this creates a product problem when multiple columns in the super schema have the same name. In order to handle these name collisions, the super schema appends the column tag to the column name of the colliding columns. The resulting schema is surprising to users as it contains column names that never existed in any schema. 

This proposal defines new semantics for the schemas of each of the diff tables: 

- `dolt_diff_$tablename` 
Use the schema from the current working root. Columns that exist in historical versions of the schema but not in the current version will not be rendered in the table.

- `dolt_commit_diff_$tablename`
Use the schema from the `to_commit` specified in the query. Missing columns will also not be rendered.

**Comment by zachmu** [comment]
The latter is kind of unworkable, because we don't want the same table to have a different schema in two different queries. Really hard to reason about SQL in that case.

Rather, the schemas of both of these tables should be taken from the schema in the root specified. If you want to see the schema from an earlier revision, use `select from dolt_commit_diff_mytable as of 'HEAD~5'`
