### ISSUE TITLE
Length of `CHAR` and `VARCHAR` types appears to pertain to physical representation

### ISSUE THREAD

**Issue by knutwannheden** [dolthub/dolt#2162]
I have an `INSERT` statement with a `VALUES` clause inserting many rows. The statement fails with an `[HY000][1105] string is too large for column` error. I think there is multiple aspects to this:

* AFAIK MySQL would typically just truncate the value and log a warning unless in strict mode (but I am not a MySQL expert).
  * I personally find this behavior of MySQL a bit weird.
* The current error is not very helpful when trying to find the source of the error. Possibly the value itself or something else could also be logged to help the user address the problem
* It appears that Dolt counts the number of bytes required to store the value (using the fixed `utf8mb4` encoding), rather than the number of characters in the value (see https://dev.mysql.com/doc/refman/8.0/en/char.html for details)

It is the last bullet which is most problematic, IMHO.

**Comment by zachmu** [comment]
Thanks for the report, Knut.

Collations are not well supported in Dolt at the moment (only one, the one golang uses), and you're correct that we use byte length rather than character length for many things. Fixing this is challenging because it involves a lot of changes to the storage layer, but it's on our roadmap and we'll be getting to it this year.

I'm going to keep this related to that primary issue and file issues for your other points.

**Comment by avilanicolas** [comment]
@zachmu Hello Zach, was wondering if you can supply an update if any work had been done for this issue since your last post. Is something still planned on the roadmap?

**Comment by zachmu** [comment]
Still on the road map. We are in the middle of making storage layer changes to make this possible. Collation support will come after that.

If this is blocking you, let us know and we'll see if we can give you a shorter term workaround.

**Comment by Hydrocharged** [comment]
@knutwannheden @avilanicolas This has been fixed! We have added proper collation support via the following PR: https://github.com/dolthub/go-mysql-server/pull/1147
