### ISSUE TITLE
Support VARCHAR(MAX)

### ISSUE THREAD

**Issue by noamross** [dolthub/dolt#2261]
Currently the maximum size for a VARCHAR is 16383 and one needs to specify VARCHAR(16383) for it. It would be nice to support the VARCHAR(MAX) syntax so one doesn't have to remember the number.

**Comment by timsehn** [comment]
This is a good first issue.

**Comment by rafimuhammad01** [comment]
Hi @noamross @timsehn I just started to contribute in open source project and I choose this issue. 

I have created PR for this issue, my approach is to check manually if the query contains VARCHAR(MAX) then I replace it with the real value which is 16383. I also implementing this in new function called validateQuery so it will be easier if we want to add more validation to the query.

Please review my PR. Thank you so much!

**Comment by rafimuhammad01** [comment]
Hi @noamross @timsehn I just look to the code and I found out that the error occur when the query is being parsed by go yacc (I don't really know about go yacc). Since you said that I need to make implementation on [go-mysql-server](https://github.com/dolthub/go-mysql-server) , I wonder about the flow of this program, Did it parse the query first in go yacc then go to the go-mysql-server or it is being process first in go-mysql-server then parse it with go yacc?

If the flow is parsing the query first with go yacc, I think I will not be able to make the implementation on go-mysql-server since the error is occur when the query being parsed with go yacc.

```go
// github.com/dolthub/vitess/go/vt/sqlparser/ast.go
func parseTokenizer(sql string, tokenizer *Tokenizer) (Statement, error) {
	if yyParsePooled(tokenizer) != 0 {
		if se, ok := tokenizer.LastError.(vterrors.SyntaxError); ok {
			return nil, vterrors.NewWithCause(vtrpcpb.Code_INVALID_ARGUMENT, tokenizer.LastError.Error(), se)
		} else {
			return nil, vterrors.New(vtrpcpb.Code_INVALID_ARGUMENT, tokenizer.LastError.Error())
		}
	}
	if tokenizer.ParseTree == nil {
		return nil, ErrEmpty
	}
	captureSelectExpressions(sql, tokenizer)
	adjustSubstatementPositions(sql, tokenizer)
	return tokenizer.ParseTree, nil
}
```
This is the code when the error occur, and I actually a bit confuse about the process, can you help me to explain it? 

Thank you!

**Comment by rafimuhammad01** [comment]
Update:

I just found out the flow, that is:
1. receive client command (in this case `create table people (id int primary key, age int, first_name varchar(80), is_married bit)`)
2. commands.SqlCmd.Exec to execute the command
3. commands.execMultiStatements
4. commands.runMultiStatements
5. commands.processQuery

then it will go to go-mysql-server and run the `CreateString(...)` function

but the the query with `MAX` will be failed in step 5 since it need to parse the query first with go yacc, so it will not get into go-mysql-server.

@fulghum @timsehn please clarify this step, just tell me if I have a mistake and if the flow is correct I think we need another approach, what do you think?

**Comment by timsehn** [comment]
It's a holiday long weekend. @fulghum will know better

I think this means our fork of Vitess (https://github.com/dolthub/vitess) needs to be modified to support this syntax. We only use the parser/server portion of Vitess.

**Comment by rafimuhammad01** [comment]
@timsehn I’m kinda confused about Vitess. Can you tell me where to start for implementing this?

**Comment by fulghum** [comment]
Hey @rafimuhammad01, good job digging in on this one! You are getting very close. 

We use a fork of the Vitess project for our MySQL wire protocol implementation as well as for the go yacc parser for SQL syntax. Here's a link to the line in our fork of Vitess where the syntax for `VARCHAR`s is defined: 
https://github.com/dolthub/vitess/blob/main/go/vt/sqlparser/sql.y#L2596

If you look up that `length_opt` rule, you'll see that's what defines the ability to specify an integer in parens for the length of a `VARCHAR` type:
https://github.com/dolthub/vitess/blob/main/go/vt/sqlparser/sql.y#L2771

If I were making this change... I would probably create a new rule called `varchar_length_opt`, copied from `length_opt`, that would allow the current alternative (`'(' INTEGRAL ')') and also have a new alternative, something like `'(' MAX ')'`. Some other things to point out:
- `MAX` is a new token that stands in for the literal value 'MAX', so would need to be defined in the `token.go` file. There might already be a `MAX` token defined, so may have to use a different name. 
- After you edit `sql.y`, you can run the go yacc tool by running `make --debug` in that `sqlparser` directory. It will regenerate the `sql.go` file that is checked into source. 
- The file `parse_test.go` should be updated with tests to make sure the syntax parses. 
- The file `ast.go` contains the hand-written AST model types that are used by the generated sql.go code to populate the model as the parser parses. You'll need to expose something so that `go-mysql-server` can ask the parser if the parsed varchar represents the `MAX` value. (We'd want that value to be plugged in at the `go-mysql-server` layer and not copied into the vitess layer just to keep everything clean and organized.)
- We should also think about other similar character types that would also want to use this new `varchar_length_opt` rule. 

After the parser supports the `MAX` syntax, then accessing that from the `go-mysql-server` layer and plugging in the max value should be super simple, so I'd focus on getting the parser work completed first. 

Let us know how it goes and if you get stuck or have any questions. We're happy to help and appreciate the contribution! 🙏

**Comment by rafimuhammad01** [comment]
Hi @fulghum, so sorry for the late response, I got a lot to do for my uni. Just want to clarify for the `varchar_length_opt` what will it return when it parse `'(' MAX ')'` ? will it return the real int value which is 16383 or just return the string of `'MAX'` ?

**Comment by fulghum** [comment]
No worries at all @rafimuhammad01; we understand this is a contribution and not your top priority task. Hope things at uni are going well!

For the new `varchar_length_opt` rule, I think it'll be a little bit cleaner if the knowledge about what is the maximum allowed varchar length stays in the go-mysql-server layer and doesn't leak into the vitess layer, so my recommendation is that the parser recognize `MAX` and instead of plugging in the value there, it sets a boolean flag that indicates the max value has been requested. Then when go-mysql-server sees that datastructure, it is responsible for plugging in the actual max value. 

I would expect the new rule to to look something like below. Note that this also requires some changes in `ast.go` in order to support the two new methods `NewVarcharLength` and `NewVarcharLengthWithMaxLength` and to define the datatype for the `varchar_length_opt` rule at the top of the `sql.y` file. 
```
varchar_length_opt:
  {
    $$ = nil
  }
| '(' INTEGRAL ')'
  {
    $$ = NewVarcharLength(NewIntVal($2))
  }
| '(' MAX ')'
  {
    $$ = NewVarcharLengthWithMaxLength();
  }
```

Hope that helps. I know yacc knowledge isn't super common, so happy to help with questions.

**Comment by rafimuhammad01** [comment]
Hi @fulghum just finished my own implementation before checking your feedback 😃. What I do is just passing the `MAX` command in go yacc so it won't return syntax error then I assign it value if I get `MAX`. What do you think about this implementation?

**Comment by fulghum** [comment]
Thanks for the contribution @rafimuhammad01! 🙏 The changes look good and I left some really minor comments. Let me know if anything doesn't make sense, and thanks again for helping us add this feature.

**Comment by rafimuhammad01** [comment]
Hi @fulghum your feedback is resolved, I have a question for the test part, please kindly check it. Thanks!

**Comment by fulghum** [comment]
Thanks @rafimuhammad01! I got your parser changes to vitess merged in and I left some comments on your go-mysql-server PR. Looks like this is very close now! Feel free to ping me here, or on Discord (as JasonF), if you hit any snags and we'll be happy to help.

**Comment by fulghum** [comment]
Great work on this one @rafimuhammad01 🙏 Your changes are in Dolt at tip of main now and will go out with the next release, probably early next week. Thanks again for picking this issue up and contributing this feature! 🎉

**Comment by noamross** [comment]
Thanks all!

**Comment by rafimuhammad01** [comment]
Thank you so much all for guiding me resolving this issue!

**Comment by rafimuhammad01** [comment]
Should we close this issue?

**Comment by fulghum** [comment]
Yup yup; I was just waiting for the release to go out, but we can go ahead and close this one out. This will go out in Dolt 0.41.5, likely in the next day or two.
