### ISSUE TITLE
dolt blame in SQL interface

### ISSUE THREAD

**Issue by noamross** [dolthub/dolt#2265]
`dolt blame` is currently only available via the CLI.  It would be good to be able to get a blame output via SQL, either as a function (`select dolt_blame('tablename');`) or a system table (`select * from dolt_blame_$TABLENAME`).

**Comment by andrew-wm-arthur** [comment]
In December we attempted to re-implement `dolt blame` using a SQL query over the `dolt_diff_$TABLENAME` system table. We were blocked at the time on bugs in window functions that have since been resolved:

https://github.com/dolthub/dolt/issues/2448

Included in the above issue is the SQL query that will replace `dolt blame` (probably). One implementation is to add a `system view` where each new table creates a new `dolt_blame_$TABLENAME` view with the above query.

**Comment by fulghum** [comment]
Thanks for the feature request @noamross. I merged a PR to main this morning that adds a new DOLT_BLAME_$TABLENAME system for querying `dolt blame` output via SQL. I'll get the reference docs updated today and this will go out in our next release. 

Resolved by: https://github.com/dolthub/dolt/pull/2754
