### ISSUE TITLE
Unexpected `--continue` behaviour for `dolt table import -u`

### ISSUE THREAD

**Issue by abmyii** [dolthub/dolt#2824]
Importing a CSV with a string value in place of an INT column fails without `--continue`, but adds a row with `0` as the value when using `--continue`.

To reproduce, clone https://www.dolthub.com/repositories/abmyii/test and run `dolt table import -u tablename test.csv --continue`.
[test.csv](https://github.com/dolthub/dolt/files/8088334/test.csv)

Note that I added a new non-PK INT column and the same thing occurred, so it isn't specific to the PK.

**Comment by VinaiRachakonda** [comment]
i can repro this. Taking a look

**Comment by VinaiRachakonda** [comment]
This why the behavior occurs:

1. --continue implements IGNORE semantics. So the command is being translated into `INSERT IGNORE INTO tablename VALUES("Abcd", 9) ON DUPLICATE KEY SET pk=VALUES(pk), col1=VALUES(col1)`
2. With IGNORE semantics MySQL will usually convert the offending column (in this case the offense is with typing) to its Zero value. Which for most types is 0. 
3. If you replicate your table in mysql and try an INSERT IGNORE you will see something similar.

I can see why this is confusing to the end user. I'm not quite sure what the correct behavior is because we want all inserts to be correctly ported through MySQL to ensure proper data integrity. Perhaps better documentation?

**Comment by VinaiRachakonda** [comment]
Yes we should support a parameter in import that shows any warnings that results from the import. Will create a separate issue

**Comment by VinaiRachakonda** [comment]
Cc #2866
