### ISSUE TITLE
Altering primary key not supported via SQL

### ISSUE THREAD

**Issue by oscarbatori** [dolthub/dolt#315]
Unclear on what the behavior should here, as we still only support tables with primary keys:
```
doltsql> alter table public_holidays drop primary key, add primary key(`date`,`localName`,`country_code`,`new_year`);
Error altering table: Unsupported alter table statement: 'alter table public_holidays drop primary key, add primary key(`date`,`localName`,`country_code`,`new_year`);'
```

**Comment by timsehn** [comment]
We have discussed this a bunch of times in the office. 

In Dolt-land, modifying primary keys should be done carefully.  

To change primary keys right now, you have to drop the table and create a new table of the same name with the primary keys you want. The reason is dolt cannot compare the two schemas. You are forking the backing store. You should also not reuse the tags for this reason. We need a better story but right now, this is the story.

**Comment by oscarbatori** [comment]
@timsehn mind if we leave it open and then pick it back up at some later date?

**Comment by timsehn** [comment]
Just wanted to have our workaround documented publicly. Happy to have this
open.

**Comment by zachmu** [comment]
@VinaiRachakonda is working on this functionality now.

**Comment by VinaiRachakonda** [comment]
This functionality is now merged into master. There are two drawbacks

1. We do not allow merge on branches with incompatible primary key sets
2. We do not allow data level diffs on commits that have different primary key sets
