### ISSUE TITLE
Retry failed clone / pull operations using already cached information

### ISSUE THREAD

**Issue by inversewd2** [dolthub/dolt#3156]
On a bad internet connection with a lot of lost packets, it can be difficult to pull large datasets. Git has the same problem when cloning large projects; however, with Git, I can use "git clone -b BRANCH URL --depth=numCommitsWanted" so that I'm not fetching the whole history in one attempt. If the dolt cone/fetch/pull commands also supported --depth, it would make it much easier to work over a bad connection.

**Comment by zachmu** [comment]
I'm taking some license with your request here. Cloning a partial history of a database is a little challenging for us with our current architecture. But we could probably do some things in the shorter term to make clone / pull on slow connections more reliable.

For starters, ideally we would reuse any table files that were pulled down in a previous clone / pull operation, rather than throwing away that work after an error. I think this might be challenging currently because the dolthub remote attempts to conjoin all the table files together into a single one on push, but I'm not positive.

**Comment by timsehn** [comment]
We do use cached information on push/pull but not clone. Like git, on a failed clone, we don't want to leave a half filled directory.

For the partial clone part, closing in favor of: #3403
