### ISSUE TITLE
`TestLoadData` fails with Dolt integrator

### ISSUE THREAD

**Issue by max-hoffman** [dolthub/dolt#3219]
The LOAD DATA INFILE Enginetests that pass in GMS were never ran against the Dolt integrator.

I added skipped `TestLoadData` in `dolt_engine_test.go`.

**Comment by VinaiRachakonda** [comment]
These tests are failing because of mismatching directories as a result of running the test case in the Dolt integrator vs GMS itself. I don't think there's a great fix for this because you can't really specify the full path in the LOAD FILE query. 

We do have `sql-load-data.bats` tests that do execute LOAD DATA queries against dolt.

**Comment by timsehn** [comment]
Going to close.
