### ISSUE TITLE
Performance concerns querying dolt_diff_<tablename>

### ISSUE THREAD

**Issue by wvl** [dolthub/dolt#3438]
We wanted to add in the UI the history of an entry in the db. (ie, what commits changed this row). This is achieved with the following query:

```
select * from dolt_diff_<table> where to_id='<id>';
```

With an imported data set of ~5000 rows and ~5000 commits, this query is taking seconds to execute.

```
1 asset - 0.016s
~1600 entries -- 0.746s
~5200 entries -- 2.4s
```

**Comment by timsehn** [comment]
As discussed performance is linear because we don't use the indexes from the table. We'll prioritize a fix.

**Comment by JCOR11599** [comment]
The senior engineers have assigned this to me, and I'll start on this immediately after I've finished my inflight work, which will likely be by the end of the week.

**Comment by andrew-wm-arthur** [comment]
The `dolt_diff_$tablename` system table exposes diffs between each commit and its parent. In the general case, querying this table requires accessing each commit in the history and its associated table set. As your benchmarks demonstrate, the amount of work is proportional to the size of the history. 

There are two ways to reduce the amount of work need for this query:

- Filtering on `to/from_commit` or `to/from_commit_date` will access only a portion of the history and reduce the number of commits accessed. This optimization has been implemented.

- Filtering on an indexed column will reduce the scope of the `diff` operation and access less table data when computing diffs. If the diff is empty for the specified range, it can significantly reduce the amount of accessed data. This optimization is not currently implemented and would take about 2 weeks to ship.

For the use case you described, the first optimization is likely not workable as it could filter out the commits that last touched an object. In this case, the cost of the query is always going to grow linearly with the history of the table. We can add some memoization to filter out commits that don't touch the table in question, but ultimately we need to compute each diff in order to know if the object in question changed.

Even if we can't change the asymptotic behavior of this query, we can still make it much faster. I put together a simple prototype of the second optimization to get a sense of how much we can improve. The benchmarking database has 5000 commits where each commit adds one row to a table:

```
mysql> select count(*) from dolt_diff_test where to_pk = 3456;
+----------+
| count(*) |
+----------+
|        1 |
+----------+
1 row in set (2.92 sec)
```
Then I added a naive implementation of the second optimization with a hardcoded index key `3456`.
```
mysql> select count(*) from dolt_diff_test where to_pk = 3456;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (1.18 sec)
```

This is better, but still not great. The proximal cause of the slowness in this cause is cost of deserializing commit and table data when accessing historical commits. This is a general problem for Dolt that we've worked extensively to alleviate. We're currently developing a new serialization format that will be released later this year. 

Running the same benchmark against this new format produces the following:
```
mysql> select to_pk from dolt_diff_test where to_pk = 3456;
+-------+
| to_pk |
+-------+
|   234 |
+-------+
1 row in set (0.10 sec)
```

**Comment by timsehn** [comment]
To be clear, we're implementing optimization (2) starting end of this week or so.

**Comment by andrew-wm-arthur** [comment]
@dphil sorry for the confusion, I think I made a mistake copy-pasting. I'll post the benchmarking setup here so you can create the repo and use it yourself.

**Comment by andrew-wm-arthur** [comment]
@dphil here's the history generating script I'm using. You can try in against the new, faster format by setting an env var `DOLT_DEFAULT_BIN_FORMAT="__DOLT_1__"`.

**Comment by JCOR11599** [comment]
There have been some improvements made regarding this issue that have been merged to main (there will be a release later today).
Filtering commits based on to_pks will now perform an index lookup.

Unfortunately, the improvements here only yield about a 1% improvement. A large amount of the work comes from traversing and deseralizing commits, so optimizing the indexed access doesn't provide much benefit.

As mentioned before, the new serialization format is much more efficient at accessing history and will make these queries much faster. It will be generally available later this year. I will continue looking into this issue, but this is where we are now.

**Comment by timsehn** [comment]
Resolving. We will be implementing benchmarks for these tables and improving their performance.
