### ISSUE TITLE
Improve logs for dolt sql

### ISSUE THREAD

**Issue by latot** [dolthub/dolt#3512]
Hi, I was testing a sql file, and I get this error.

```
./dolt sql < ../water/test.sql
+
|
+
+
invalid GIS data provided to function GeometryType.Convert
```

Well, this issue is not above the error in the query, is the lack of info to know where and how is failing, I think this can be improved.

Thx.

**Comment by fulghum** [comment]
Thanks for providing this feedback @latot. I tried a couple of simple examples and got an error message with the line number of the failing statement and a description of the problem. I'm guessing that specific statements or more complex sql input files cause the error message you see that doesn't contain enough helpful info to debug. If you're able to share the contents of the `test.sql` file, I'd be happy to try to reproduce and see what we can do.

**Comment by fulghum** [comment]
Sorry for the delay on this one @latot – I had some other tasks on my stack, but I'm digging into this one now. I was able to repro the error message you provided and I'll get a PR out today so that Dolt provides a better error message that explains exactly what the problem was. 

btw, the underlying issue is that the import file contains geospatial types that Dolt doesn't support yet. MultiLineString, MultiPolygon, MultiPoint, and GeometryCollection are currently not supported so when the import code encountered one, it just gave that vague error message about not being able to convert a value.

**Comment by fulghum** [comment]
Thanks again for reporting this @latot and also for opening an issue to track implementation of the remaining spatial types. 

I've got an improved error message built out for go-mysql-server and will be pulling it into Dolt this afternoon, along with another error message improvement at the Dolt layer to show the line number. We'll get those out in a release next week. 

Here's what the error message looks like with these new changes (I truncated below, but the real output shows the full value that was trying to be converted): 
```
❯ dolt sql < test.sql 
+
|
+
+
error executing query on line 43: unsupported geospatial type: MultiPolygon from value: 0x010000000106... 
```
