### ISSUE TITLE
`dolt init --user --email` isn't respected in succeeding commits

### ISSUE THREAD

**Issue by kretes** [dolthub/dolt#3546]
`dolt init --help` says:
```
 --name=<name>
          The name used in commits to this repo. If not provided will be taken from user.name in the global config.
```
however when invoked with this switch - the name isn't used for succeeding commits. See:

```
:/tmp/doltrepo# dolt init --name='unit tester' --email='unit.tester@sth'
Successfully initialized dolt data repository.

:/tmp/doltrepo# dolt status
On branch main
nothing to commit, working tree clean

:/tmp/doltrepo# dolt sql
# Welcome to the DoltSQL shell.
# Statements must be terminated with ';'.
# "exit" or "quit" (or Ctrl-D) to exit.
doltrepo> create table a(id int);
doltrepo> ^D
Bye

:/tmp/doltrepo# dolt add a  

:/tmp/doltrepo# dolt commit -m 'can I?'
Author identity unknown

*** Please tell me who you are.
[...]
```

**Comment by fulghum** [comment]
Hey Tomasz, thanks for reporting this. I was able to repro – despite passing `name` and `email` in with the call to init, the local repo config doesn't seem to get set correctly. I'll keep digging in and see what we find...

**Comment by fulghum** [comment]
Hey @kretes, this one is fixed in https://github.com/dolthub/dolt/pull/3549 and merged to main now. We’ll run a release later this week, but just let me know if you’re waiting on that release and want one faster – I'd be happy to run one sooner if you need it. 

Thanks again for reporting this so we could fix it! 🙏
