### ISSUE TITLE
prepare binding failed when fields length more than 65535

### ISSUE THREAD

**Issue by wupeaking** [dolthub/dolt#3728]
dolt version: v0.40.11

mysql driver: go-mysql-driver

issue:
when I insert large char it returns an error. (Error 1105: length is 94420 but max allowed is 65535)
the dolt log: `2022-06-30T10:37:58+08:00 ERROR [conn 155] Error processing bindings {connectTime=2022-06-30T10:37:58+08:00, connectionDb=dolt_example, error=length is 94420 but max allowed is 65535, query=replace into ad_lanedivider(edge_id, id, tag, width, geometry, cfd_post, confidence_xconf, confidence_yconf, confidence_xcov, confidence_ycov, fusion_count, create_time, update_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`

but it works when I insert values to tables not using placeholder. 

I have set max_allowed_packet=1024 * 1024 * 1024;

**Comment by timsehn** [comment]
Thanks. We'll try and repro today and see if there is an easy fix.

**Comment by fulghum** [comment]
Thanks for reporting this one @wupeaking. 

I was able to repro the failure with a prepared statement. This is working as expected since the length of the prepared statement value (94,420) is larger than the max possible byte length of a `varchar` column (65,535). 

However, I was **not** able to repro successfully inserting the same value into the table with a non-prepared statement. My test performed as expected and returned this error message _(actual string value truncated here)_: `Error 1105: string '0...0' is too large for column 'vc'`.

I had to make some assumptions in my test, so I might be missing something important from your setup. If you're able to share more details on your repro, I'd be happy to keep poking around and see if we can find something. Having a script of the exact sql commands/values for a minimal repro would be the easiest way to make sure we're testing the exact same thing. If that's not possible, the output from `show create table ad_lanedivider` (so I can see the schema) and the full sql statement and values would also help.

**Comment by wupeaking** [comment]
Hi， I write an simple demo repo it.

the schama is :
```sql
CREATE TABLE dolt_example.large_char_issue (
	seq_id INT UNSIGNED auto_increment NOT NULL ,
    id varchar(128) NOT NULL primary key, -- uid
	geometry JSON , -- geojson格式
	index(seq_id)
)
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_bin;
```

I push the code files because chars is large.
[demo.zip](https://github.com/dolthub/dolt/files/9024661/demo.zip)

**Comment by fulghum** [comment]
This looks awesome; thanks for taking the time to provide all this for a repro. I'll get started with this right away and let you know what I find.

**Comment by fulghum** [comment]
Thanks again for the awesome repro information. That was a big help to narrow in on the problem. I see now that you’re using a JSON column – I wasn’t testing with that before. I’ve now reproed the failure with a bind var and you’re correct that this case should work. 

I’ve also confirmed that not using bind bars allows this query to execute correctly with Dolt and that both forms work correctly with MySQL, as expected. 

The logic in the go-mysql-server is only doing that length check when converting bind vars into expressions and there’s no easy signal at that layer that the bind var is for a JSON type – it’s sent over the wire as a VARBINARY type. 

My initial instinct is that this length validation logic should be moved to a different layer (perhaps just for data that comes in as VARBINARY type over the wire). I’ll keep digging in deeper, experiment with a few options, and will keep you updated. We'll get this working and appreciate the bug report.

**Comment by fulghum** [comment]
One last, quick update before the weekend. I started experimenting with removing the validation and confirmed that’s the only thing that is preventing the statement with bind vars from executing correctly. I suspect that the right fix is moving some of the validation logic, and will keep digging into the details and doing some more testing to make sure that doesn’t break anything else. Also, just a quick heads up that Monday is a US holiday, so we’ll get you another update on progress on Tuesday.

**Comment by wupeaking** [comment]
@fulghum Thanks for the quick response. I'm in the preparatory stage of some database selection. I will do more testing next time. If there are other problems I will report to you in time. 😄

**Comment by fulghum** [comment]
Heya @wupeaking, I just merged in a fix for this issue and we'll get it shipped out in the next Dolt release. That'll likely be later this week, but let me know if you'd like to try out a build with this fix sooner and I'd be happy to cut a release earlier for you. 

Thanks for reporting this issue so we could get it fixed!
