### ISSUE TITLE
Implement `dolt init --fun`

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#4015]
The dolt logo is inspired by a commit hash `d01t`. 

It would be cool if we had an option to have a dolt initial commit be rerolled until the first four characters matched the following pattern:

1. d, o l, t in order 
2. any uppercase or lowercase d, o, l, t
3. 0 or 1 can replace l or t

I think this should be a hidden option not in the docs.

**Comment by solipsis-project** [comment]
This seems like a fun way to get my feet wet.

My first instinct was something similar to https://github.com/dolthub/dolt/pull/4033, except instead of polluting the commit_options struct, we tweak the Database interface to let its caller (in this case the DoltDB library) create a commit itself and reroll it as needed before passing it to `Databse.Commit`

But it's still not great. We're making the Database interface more complicated for no real benefit. And we still need to pass an extra parameter to every method between `InitCmd` and here, so a lot of method signatures get more cluttered.

And yet I'm hesitant to go with the alternative solution proposed in the pull request (deleting and recreating the repo repeatedly) because that's a lot of FS access that should, in theory, be completely unnecessary. @abmyii reported it being horrendously slow, and I believe them.

Either way, the hardest part would be to make this a hidden option, since the ArgParser currently has no notion of hidden options, and the help text is generated directly from the ArgParser's list of supported options.

At this point it's worth wondering if a fun easter egg justifies these interface complications.

**Comment by timsehn** [comment]
LOLZ. I was thinking about suggesting this one as a good way to get familiar.

Then I was like, though cool, did I learn that it wasn't worth it from @abmyii's attempt?

I don't think @abmyii ever got the blow away, re-roll option working. I think even if that is slow, having your init commit hash be some form of "dolt" is cool. 

Looks like you can roll about 20 times per second with this approach.
```
$ time dolt init && rm -r .dolt
Successfully initialized dolt data repository.
dolt init  0.06s user 0.06s system 77% cpu 0.162 total
```

How long do we think it would take at 20 rolls per second?

**Comment by timsehn** [comment]
The other option may be to resurrect @abmyii 's branch and just have it so if you want this you have to build from that branch. Not sure how long it would live that a dolt init off the special branch would be valid though.

**Comment by solipsis-project** [comment]
> How long do we think it would take at 20 rolls per second?

Well, let's do some back of the napkin math. Base32 means 32**4 options for the first four characters. That's 2**20, about 1 million.

Of those 1 million possibilities, we have 1*2*2*1 = 4 acceptable strings. (The original issue mentions that uppercase letters should be allowed, but our base32 encoding only uses lowercase letters. We're lucky though: standard base32 also skips 0 and 1 because of the similarity to o and l, but the dolt implementation chooses to skip wxyz instead.)

 So on average, we'll get a match every (2**20/4) = about 262k tries. At 20 rolls a second, we expect to need 13107 seconds, which is 218 minutes, roughly three and a half hours. And of course, the storage media being used could affect this number a lot.

That's also a lot of writes if you're using flash media.

**Comment by solipsis-project** [comment]
Let's compare that to my local branch, which is pretty similar to @abmyii's.

I ran it and recorded the number of attempts. I got unlucky: it took 376917 tries, about 40% more than expected. The runtime? 2.96 seconds. Roughly 126k per second.

This conversation actually helped me identify a bug in my implementation: when I was first gathering the numbers for this, I observed it taking on the order of 10s of millions of attempts to find a match, more than expected by an order of magnitude. The ultimate culprit? While the `time` library has nanosecond precision, the timestamps are truncated to millisecond precision within the commit struct, and so making small changes to the timestamp wasn't changing the hash.

The downside of this is that 262k tries, changing the timestamp by 1ms each time, gives us timestamps that are, on average, around 4.5 minutes away from the present, which is definitely going to be noticeable.

I pushed my local branch to https://github.com/solipsis-project/dolt/tree/fun_commits so it can serve as an example, but I don't have any intention of making a pull request right now.

**Comment by fulghum** [comment]
Very nice analysis for this! I didn't closely compare the two implementations, but rolling a new commit 126k times per second seems pretty good. I'm guessing that number is so much higher than Tim's 20 per-second ballpark since it doesn't have all the process and go startup costs in it (as well as the `rm` cost). 

If we **do** want to ship this easter egg, I think the tradeoff with the commit time being slightly inaccurate could be okay – especially since you are subtracting 1ms instead of adding, so at least the commit time wouldn't be **after** future commits made in the next few minutes. Not ideal of course, but could be a reasonable tradeoff if someone *really* wants this easter egg.

**Comment by timsehn** [comment]
I wants it!

**Comment by solipsis-project** [comment]
Another reason it's faster is because my implementation doesn't write the commit to the database (and thus the file system) at all until it finds a match.

If we go down this route, we'd need to decide between @abmyii's version and mine. My version adds an extra method to the `Database` interface in order to inspect a generated commit before writing it to the DB, but honestly I'm surprised there's not already an option for that, and I can think of potential situations where we would need to support that anyway ("dry runs", concurrent DB access, etc). And it seems less invasive than their approach, adding a field to the CommitMeta struct, which shouldn't need to store whether we're using this Easter egg or not.

Lastly, if we wanted to we could cut down on the timestamp drift by finding other ways to tweak the commit. (Adding zero-width spaces in the commit message? Jk)

**Comment by solipsis-project** [comment]
Actually, I thought of another way to reroll commits that doesn't require altering the timestamp, although the algorithm would be a little more complicated: unicode homoglyphs.

The commit message is stored in UTF-8, and Cyrillic contains homoglyphs for a, e, i, and o that appear identical in most fonts. That's 12 characters in the commit message that can be toggled, reducing the timestamp drift by a factor of 2^12, enough to make it imperceptible.

Of course, the challenge becomes how to architect this, given that the code that creates the commit struct doesn't (and shouldn't) assume a hardcoded commit message.

**Comment by abmyii** [comment]
@solipsis-project Thanks for taking a second shot at this and getting some great results! I was getting 3-5 mins in my initial PR which seems to beat the 218 min estimate, but it modified stuff much lower than the application layer which started to become unwieldy. My second PR seemed to get stuck in infinite loops, and I that was due to "time misses" where the interval between retries was too long, missing timestamps that would have produced good hashes.

Perhaps a hybrid approach might work better? Also, regarding modifying time, couldn't you simply use the current time which will naturally be progressing (forward rather than backward)?

**Comment by solipsis-project** [comment]
The timestamp skew is now a thing of the past: By replacing Latin characters with Cyrillic characters in the commit message, we can generate 2^12 different possible commits per timestamp, making the timestamp skew imperceptible.

I'm going to add a BATS test to confirm that using the flag produces an expected hash, then make a pull request. There's already a BATS test that confirms that the commit message isn't altered when --fun isn't passed. We might want a BATS test to confirm the commit message for  this easter egg, if we have a way of normalizing Unicode homoglyphs.

**Comment by solipsis-project** [comment]
@abmyii The problem with using the current time is that the commits only store the timestamp to the millisecond, so using the current timestamp capped our efficiency at one commit per ms, when we're capable of checking hundreds of commits in that time. This was what lead to the 3-5 mins you were observing.

With the Unicode homoglyphs approach, this is no longer an issue, but since the timestamp gets passed into the DoltDB, it's easier to just manipulate it than get another one.

**Comment by solipsis-project** [comment]
As a side note, I feel like this implementation is right on the border between deserving its own function so it stops cluttering up the actual important business logic. We could probably refactor this into goroutine generator that produces all the different hashes and the main logic iterates over them.

**Comment by solipsis-project** [comment]
Worth noting: Using Unicode homoglyphs won't work on terminals that don't support Unicode, such as Powershell on Windows in its default setting.

(Did you know that Powershell on Windows assumes Windows-1252 encoding by default? Only the Windows version does this.)
