### ISSUE TITLE
`count(*)` in new format 3X slower for large table

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#4123]
Old format:
```
us-housing-prices $ time dolt sql -q "select count(*) from sales"
+----------+
| count(*) |
+----------+
| 86938108 |
+----------+

real    1m11.206s
user    10m22.097s
sys    2m29.339s
```

New format:
```
us-housing-prices-v2 $ time dolt sql -q "select count(*) from sales"
+----------+
| count(*) |
+----------+
| 86937691 |
+----------+

real    3m0.009s
user    22m38.836s
sys    9m2.448s
```

**Comment by andrew-wm-arthur** [comment]
A hypothesis is that the old format is more efficient at loading table partitions because it leverages the `ChunkStore.GetMany()` api, which can read an entire leaf range from disk in one pass. In contrast, the new format loads each chunk in the partition as the iterator reaches it.

[old format range iteration](https://github.com/dolthub/dolt/blob/82fedd05a7f8ae21630037cfd24a5569bbcca00c/go/store/types/map_iterator.go#L129) vs [new format range iteration](https://github.com/dolthub/dolt/blob/82fedd05a7f8ae21630037cfd24a5569bbcca00c/go/store/prolly/ordered_tree.go#L218)

**Comment by andrew-wm-arthur** [comment]
https://github.com/dolthub/dolt/pull/4202 partially addresses this issue by utilizing `ChunkStore.GetMany()` to batch read chunks from table files. Format `__DOLT__` is still slightly slower on the above query *`81s` vs `87s` on my machine), but is relatively faster when considering the newer repo is larger (`64GB` vs `47GB`).

**Comment by timsehn** [comment]
This is beautiful.
