### ISSUE TITLE
Unresolved Column panic

### ISSUE THREAD

**Issue by andrew-wm-arthur** [dolthub/dolt#4182]
`panic: unresolved column is a placeholder node, but Type was called`

[Dolthub database](https://www.dolthub.com/repositories/dolthub/nautobot-version-control-plungin) for repro

```
SELECT COUNT(*) FROM (SELECT (SELECT U2.`name` FROM `circuits_circuittermination` U0 INNER JOIN `circuits_circuit` U1 ON (U0.`circuit_id` = U1.`id`) INNER JOIN `dcim_site` U2 ON (U0.`site_id` = U2.`id`) INNER JOIN `circuits_provider` ON (U1.`provider_id` = `circuits_provider`.`id`) WHERE (U0.`circuit_id` = `circuits_circuit`.`id` AND U0.`term_side` = 'A') ORDER BY `circuits_provider`.`name` ASC, U1.`cid` ASC, U0.`term_side` ASC LIMIT 1) AS `a_side`, (SELECT U2.`name` FROM `circuits_circuittermination` U0 INNER JOIN `circuits_circuit` U1 ON (U0.`circuit_id` = U1.`id`) INNER JOIN `dcim_site` U2 ON (U0.`site_id` = U2.`id`) INNER JOIN `circuits_provider` ON (U1.`provider_id` = `circuits_provider`.`id`) WHERE (U0.`circuit_id` = `circuits_circuit`.`id` AND U0.`term_side` = 'Z') ORDER BY `circuits_provider`.`name` ASC, U1.`cid` ASC, U0.`term_side` ASC LIMIT 1) AS `z_side` FROM `circuits_circuit` WHERE `circuits_circuit`.`provider_id` = 'b37b4cece82d4b4db267eccb1518ba4c') subquery
```

**Comment by JCOR11599** [comment]
It turns out @fulghum's PR: https://github.com/dolthub/go-mysql-server/pull/1214 fixes this issue.

The `SELECT (SELECT ...))` statement was throwing a table alias error.
However, since that query is embedded inside of a subquery, the error wasn't returned, and instead the analyzer deferred resolving the column till later. Eventually, it reaches the end of the analysis process and the improperly aliased column remains unresolved, and we panic.

Jason's changes alias the columns with capital letters properly, so the columns are resolved, so no errors are captured, so no columns are deferred, and nothing panics.
