### ISSUE TITLE
Support `uptime` global variable. 

### ISSUE THREAD

**Issue by joel-rieke** [dolthub/dolt#4473]
Can you provide support for the command:
SHOW GLOBAL STATUS LIKE 'Uptime'

**Comment by JCOR11599** [comment]
Hey @joel-rieke, I'm working on a fix for this here: https://github.com/dolthub/go-mysql-server/pull/1415

Could you tell us a little more about how you're using these variables?
For example, are you using a specific tool, like DBeaver, and getting an error because one of these status variables are missing.
Additionally, do you know which specific variables you'd like to be included / implemented?

For context, we currently include variables from these places:
https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html
https://dev.mysql.com/doc/refman/8.0/en/replication-options-gtids.html
https://dev.mysql.com/doc/refman/8.0/en/replication-options-source.html

But don't have the variables listed here:
https://dev.mysql.com/doc/refman/8.0/en/mysql-cluster-options-variables.html
https://dev.mysql.com/doc/refman/8.0/en/server-system-variable-reference.html

**Comment by joel-rieke** [comment]
Yes, just using a database client.  When I run the command, I get an empty result set.  I guess it could be my user too.  Are any special GRANTS required to execute this command?

**Comment by JCOR11599** [comment]
There are no special grants necessary, we've just been returning an empty table.
What database client are you using?

**Comment by joel-rieke** [comment]
I use a linux version of dbvisualizer with mariadb 'driver'.

**Comment by JCOR11599** [comment]
Hey @joel-rieke, the newest dolt release [`v.51.5`](https://github.com/dolthub/dolt/releases/tag/v0.51.5) now supports `SHOW STATUS`. Try it out and let us know if there are any specific system variables missing that you want.

**Comment by joel-rieke** [comment]
Very cool. :)

**Comment by joel-rieke** [comment]
Ok, I just tried the latest.  When I run Show Status, I now get some variables returned.  I think what I was hoping for some kind of system uptime variable:

It's nice for the database to know how long it has been up.

**Comment by JCOR11599** [comment]
Hey @joel-rieke, the `show status like 'uptime'` should work in the release that just came out (`v0.51.6`).
