### ISSUE TITLE
sql.JsonDocument ToString returns strings without whitespaces

### ISSUE THREAD

**Issue by druvv** [dolthub/dolt#4499]
The `sql.JsonDocument` `ToString` method uses `json.Marshall`. This returns a string without any extraneous whitespace. MySQL on the other hand uses whitespaces for legibility:

```
mysql> CREATE TABLE t1 (c1 JSON);

mysql> INSERT INTO t1 VALUES
     >     ('{"x": 17, "x": "red"}'),
     >     ('{"x": 17, "x": "red", "x": [3, 5, 7]}');

mysql> SELECT c1 FROM t1;
+------------------+
| c1               |
+------------------+
| {"x": "red"}     |
| {"x": [3, 5, 7]} |
+------------------+
```

Notice that there is additional whitespace between the semicolon of a key/value pairs and between the comma of array elements.

In Dolt's new storage format, we use sql.JsonDocument for JSON columns. Previously we used [json.NomsJson](https://github.com/dolthub/dolt/blob/08479ce24b5f585f571c45a28e1e82eb9311c499/go/libraries/doltcore/sqle/json/noms_json_value.go#L36) which implements `ToString` correctly.

**Comment by GuillermoMajano** [comment]
can i take this?

**Comment by timsehn** [comment]
Definitely. Here's the contributors guide:

https://docs.dolthub.com/guides/contributing/go-mysql-server

**Comment by PavelSafronov** [comment]
@GuillermoMajano , this bug is on a critical path of a paying customer, so I started work on it last night and might have a fix.
You're welcome to continue working on it, of course, as it's still a good introduction into the codebase. Or feel free to start on a different issue. I just don't want you to end up wasting time.
