### ISSUE TITLE
sql-server: `kill query` spam with parameterized statements

### ISSUE THREAD

**Issue by nairb774** [dolthub/dolt#4601]
For every parameterized query that is issued, the sql-server seems to generate a `INFO [no conn] kill query: pid 1089 {}` style line on connection close. If a connection is used to issue large volumes of queries, then the log spam can be quite significant.

The following code can be run against an empty `dolt sql-server`:
```golang
package main

import (
        "database/sql"
        "flag"

        _ "github.com/go-sql-driver/mysql"
)

var dbURI = flag.String("db", "", "URL of MySQL DB to connect to")

func main() {
        flag.Parse()

        db, err := sql.Open("mysql", *dbURI)
        if err != nil {
                panic(err)
        }
        defer db.Close()

        // Change loop count to generate a log line per iteration:
        for i := 0; i < 5; i++ {
                var out int64
                if err := db.QueryRow("SELECT ?", 1).Scan(&out); err != nil {
                        panic(err)
                }
        }
}
```

Issuing a query like `SELECT 1` doesn't cause log spam. I couldn't find any use of the `database/sql` APIs that would avoid the log spam when using parameters.

`go.mod` for good measure:
```golang
module repro

go 1.19

require github.com/go-sql-driver/mysql v1.6.0
```

And `dolt` version:
```
$ dolt version
dolt version 0.50.8
database storage format: NEW ( __DOLT__ )
```

It seems like some internal resource isn't being released correctly until the connection itself is closed.

**Comment by bpf120** [comment]
Hi @nairb774, Thanks for the report. We'd love to learn more about your use case too. Feel free to [email me](mailto:brianf@dolthub.com) me or swing by our [Discord](https://discord.com/invite/RFwfYpu) if you want to share.

**Comment by fulghum** [comment]
Thanks for taking the time to open this issue and send us a nice repro case @nairb774. I debugged through this, and it looks like the PID for the prepared statement is getting set once, then registering itself with the `ProcessList` using that PID, but then the PID gets incremented again, and the later call to `ProcessList.Done(PID)` doesn't find the entry registered with the first PID. I'm going to dig in a little more to confirm that's what's happening, then start looking for the right fix.

**Comment by fulghum** [comment]
I've got a working fix coded up for this issue – when we pull a previously analyzed statement, we need to update that execution plan so that it is not pinned to the `context.PID` that was used when the prepared statement was analyzed, but instead uses the `context.PID` for the current statement's execution. 

I'll tidy the code up a bit more tomorrow and then get this fix out for review. Thanks again for helping us find this issue so we could fix it!

**Comment by fulghum** [comment]
Hey @nairb774, just wanted to thank you again for opening this issue so we could get to the bottom of this. Dolt/go-mysql-server was indeed not properly tracking processes for prepared statements and was also leaving metadata around that could build up, like you mentioned. 

The fix is merged to main in go-mysql-server now, and we'll get it into Dolt and out in the next Dolt release, likely by the end of this week or early next week. Don't hesitate to let us know if you need a build sooner for any reason and I'd be more than happy to run a release for you.
