### ISSUE TITLE
Inserted rows not persisting on switched branch

### ISSUE THREAD

**Issue by dphil** [dolthub/dolt#4863]
Reproduced with both dolt 0.51.4 and 0.51.5 on Ubuntu 20.04.5. Not tested on earlier dolt versions.

Steps to reproduce:

Setup simple db with 2 branches
```
$ mkdir testdb
$ cd testdb
$ dolt init
$ dolt sql -q "create table users (id int, name varchar(255));"
$ dolt add -A
$ dolt commit -am "created users table"
$ dolt branch -c main feature
```

Run a dolt server in the parent directory of this db.
Next, connect to the db, switch to the feature branch, and insert data into the users table.

```
$ dolt sql-client -u root
# Welcome to the Dolt MySQL client.
# Statements must be terminated with ';'.
# "exit" or "quit" (or Ctrl-D) to exit.
mysql> use testdb;
mysql> select active_branch();
+-----------------+
| active_branch() |
+-----------------+
| main            |
+-----------------+
1 row in set (0.00 sec)

mysql> call dolt_checkout('feature');
+--------+
| status |
+--------+
| 0      |
+--------+
1 row in set (0.00 sec)

mysql> select * from users;
mysql> insert into users values (0, 'alfred');
mysql> select * from users;
+----+--------+
| id | name   |
+----+--------+
| 0  | alfred |
+----+--------+
1 row in set (0.00 sec)

mysql> exit
```

Next, kill the dolt server.
In the cli, switch to the feature branch and try to display the newly-added user:
```
$ dolt checkout feature
$ dolt sql -q "select * from users;"

$
```
There is no result. `dolt status` shows no changes either.

If you do not switch branches, it all works as expected. ie you connect to the running server, use your db, but stay in the default main branch (no `call dolt_checkout('feature')`) and insert a user there, then exit the client and query the users table - the user exists.

**Comment by zachmu** [comment]
This is a bug.

In the SQL server, checking out a branch doesn't make any changes to the working set at the destination branch.

On the command line, checking out a branch copies the working set from the source to the destination. This is to copy git's behavior. But it has the nasty side effect of stomping any working set at the destination. This isn't an issue git has to deal with (impossible to have more than a single working set, while dolt with SQL server has 1 per branch).

The fix is that `dolt checkout` should fail if the destination branch has working set changes that aren't in that branch's HEAD.
