### ISSUE TITLE
Change (error?) in the handling of window functions between 0.50.14 and 0.50.15

### ISSUE THREAD

**Issue by swaldman** [dolthub/dolt#4962]
A while back, I wrote a query abusing window functions and nested queries to convert annual GDP levels data to growth rates by decade. You can see it on dolthub [here](https://www.dolthub.com/repositories/swaldman/fredselect/query/main?name=Real+GDP+Growth+By+Decade&active=Queries). 

```
select 
  decade, 
  (last/laglast - 1) * 100 as real_gdp_growth 
from (
  select 
    observation_date, 
    decade, 
    lag(last) over (order by observation_date) as laglast, 
    last 
  from (
    select 
      observation_date, 
      decade, 
      last_value(value) over w as last, 
      value 
    from (
      select 
        observation_date, 
        (YEAR(observation_date)/10) * 10 AS decade, 
        value 
      from 
        GDPCA
    ) as gdp_decade 
    window w as (partition by decade order by observation_date range between unbounded preceding and unbounded following)
  ) as gdp_decade_last 
  order by observation_date
) as gdp_growth_by_decade 
where last != laglast and decade < 2020
```

It's intended to, and up to `0.50.14` did, generate a table like this:

```
+--------+--------------------+
| decade | real_gdp_growth    |  <-- 0.50.14
+--------+--------------------+
| 1930   | 10.178651529535966 |
| 1940   | 72.33336875924819  |
| 1950   | 50.86439794326279  |
| 1960   | 55.49977674500506  |
| 1970   | 37.12035929536211  |
| 1980   | 35.645186408224006 |
| 1990   | 37.24032525777081  |
| 2000   | 20.69893271688894  |
| 2010   | 24.939122207271037 |
+--------+--------------------+
```

However, the behavior changes in `0.50.15`, so that it no longer succeeds at collapsing the data into decades:

```
+--------+----------------------+
| decade | real_gdp_growth      |  <-- 0.50.15
+--------+----------------------+
| 1930   | -8.507880519471156   |
| 1931   | -6.405605310750362   |
| 1932   | -12.898580603900767  |
| 1933   | -1.236261579762854   |
| 1934   | 10.807826622843052   |
| 1935   | 8.904308369003754    |
| 1936   | 12.88340823078209    |
| 1937   | 5.124715901950716    |
| 1938   | -3.313512258099771   |
| 1939   | 8.025165630756902    |
| 1940   | 8.816965198126226    |
| 1941   | 17.71430288642135    |
| 1942   | 18.886579936279713   |
...
| 2017   | 2.2419166128307744   |
| 2018   | 2.945385182244209    |
| 2019   | 2.294439305375562    |
+--------+----------------------+
```
Either something has broken, or I was relying on something that was broken but is now inconveniently fixed!

**Comment by fulghum** [comment]
Hey @swaldman, thanks for taking the time to report this. This is a neat query! 

The behavior change is coming from this line:
```sql
select 
        observation_date, 
        (YEAR(observation_date)/10) * 10 AS decade
```

We recently made some fixes to arithmetic operations and this line now behaves the same as MySQL and returns values such as `2022.0000`.  Here's a quick repro with MySQL:
```sql
mysql> select YEAR(DATE("2022-01-01")) / 10 * 10 as decade;
+-----------+
| decade    |
+-----------+
| 2022.0000 |
+-----------+
```

Older versions of Dolt were incorrectly dropping all the decimal digits when the year type was divided by 10, so that's why the query was working for you previously. 

Fortunately, the fix is super easy – just use `div` for integer division instead of `/` for floating point division in your query. [Here it is in the DoltHub console](https://www.dolthub.com/repositories/swaldman/fredselect/query/main?active=Tables&q=select+decade%2C+%28last%2Flaglast+-+1%29+*+100+as+real_gdp_growth+from+%28select+observation_date%2C+decade%2C+lag%28last%29+over+%28order+by+observation_date%29+as+laglast%2C+last+from+%28select+observation_date%2C+decade%2C+last_value%28value%29+over+w+as+last%2C+value+from+%28select+observation_date%2C+%28YEAR%28observation_date%29+div+10%29+*+10+AS+decade%2C+value+from+GDPCA%29+as+gdp_decade+window+w+as+%28partition+by+decade+order+by+observation_date+range+between+unbounded+preceding+and+unbounded+following%29%29+as+gdp_decade_last+order+by+observation_date%29+as+gdp_growth_by_decade+where+last+%21%3D+laglast+and+decade+%3C+2020), and I've also included it below: 
```sql
select 
  decade, 
  (last/laglast - 1) * 100 as real_gdp_growth 
from (
  select 
    observation_date, 
    decade, 
    lag(last) over (order by observation_date) as laglast, 
    last 
  from (
    select 
      observation_date, 
      decade, 
      last_value(value) over w as last, 
      value 
    from (
      select 
        observation_date, 
        (YEAR(observation_date) div 10) * 10 AS decade, 
        value 
      from 
        GDPCA
    ) as gdp_decade 
    window w as (partition by decade order by observation_date range between unbounded preceding and unbounded following)
  ) as gdp_decade_last 
  order by observation_date
) as gdp_growth_by_decade 
where last != laglast and decade < 2020
```

Apologies that this bit you!! We strive to match all of MySQL's behavior and semantics exactly, and we apologize if those fixes break queries that were relying on the older behavior in Dolt. Hopefully you won't hit one of those again!

Thanks for reporting this one so we could explain the change and suggest a query modification. Please don't hesitate to ping us again if you see anything odd or just have any questions we can help you out with.

**Comment by timsehn** [comment]
Let us know if this doesn't fix it for you :-)

**Comment by swaldman** [comment]
Thanks @fulghum @timsehn! It makes sense that you'll try to converge dolt behavior pretty precisely, and replacing `/` with `DIV` did the trick to restore the functionality of the queries. I'll try to remember to use DIV for integral, drop-the-remainder division from now on.
