### ISSUE TITLE
`git-dolt update` should be able to update dolt repo and handle branch references

### ISSUE THREAD

**Issue by tomdottom** [dolthub/dolt#515]
As far as I can ascertain the `git-dolt` command is intended to deterministically checkout data from one of more dolt repos into a git repo.

For example the following will clone a dolt repo into a git repo:
```
# 1. Installs git smudge filters
git dolt install   
                                    
# 2. Clone dolt repo `master` and create a pointer file covid-tracking.git-dolt 
#    with commit hash
git dolt link tomdottom/covid-tracking                   
```

Subsequent checkouts can clone/checkout the same data using
```
# 1. Clone git repo & cd into it
# 2. Clone dolt repo at commit hash saved in pointer file covid-tracking.git-dolt
git dolt fetch covid-tracking.git-dolt
```

We can also update the commit hash in the pointer file with:
```
git dolt update covid-tracking.git-dolt l9ockrbk9muv9vr32oht1ift0qr38gpq
```

However, the only current ways to update the revision checked out in the dolt repo are:

1. Brutally delete dolt repo, and re-clone:
```
rm -r covid-tracking
git dolt fetch covid-tracking.git-dolt
```

2. Forcefully update the dolt repo branch to the same commit used in the update command:
```
cd covid-tracking
dolt branch -f git-dolt-pinned l9ockrbk9muv9vr32oht1ift0qr38gpq
cd ..
```

Neither of these feel right/natural.

Ideally manipulating the dolt repo could be done by the update command. The command would look the same:
```
# Update the checked out data in the dolt repo and update the revison in the pointer file
git dolt update covid-tracking.git-dolt l9ockrbk9muv9vr32oht1ift0qr38gpq
```

In addition when updating using a branch reference the HEAD commit should be saved to the pointer file, not the branch name (as it currently does). Note this is the same behaviour as the current link command. 
```
# Check out 'master' and save the HEAD commit to the link file
git dolt update covid-tracking.git-dolt master
```

Or you could make this more explicit with:
```
git dolt update covid-tracking.git-dolt --branch=master
```

Similarly the link command could also take a revision or branch reference:
```
git dolt link tomdottom/covid-tracking master
# or
git dolt link tomdottom/covid-tracking --branch=master
```

Lastly, if the pointer file contained a branch reference the `git dolt` tool could pull the latest commit if needed, say with:
```
# Checkout HEAD of saved branch and save revision to pointer file
git dolt pull covid-tracking.git-dolt
```

Hope insights from fresh eyes help.  Then again you may have already thought of something better.

Cheers,

Tom

**Comment by mjesuele** [comment]
Hi Tom, I'm the original author of `git-dolt`. We developed it a little while back as a proof-of-concept and haven't worked on it much since, but seeing someone interested enough in it to post such a detailed and helpful issue is exactly the kind of signal we need to pick it back up.

I like your suggestions. I definitely agree that `link` (and other commands) should be able to accept any commitish reference, and I like the idea of having `update` also check out the revision specified. `fetch` should definitely be better-behaved as well. `git dolt pull` sounds like a solid addition.

I'm pretty busy with other projects right now but if this is something you're very interested in and/or have a serious use for, we can reprioritize things on our end. Or if you'd rather not wait, you can take a crack at implementing it yourself and we'll happily review and accept your changes.

Thanks for the feedback!

Matt

**Comment by timsehn** [comment]
`git-dolt` is deprecated.
