### ISSUE TITLE
Implement add/remove backup in `dolt_backup()` stored procedure

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#5243]
Customer asked for it.

```
$ dolt sql-client -u root -q "call dolt_backup('add', 'test', 'file:///tmp/')"
Error 1105: adding backup endpoint in sql is unimplemented.
```

**Comment by PrathyushaModala** [comment]
Hi @timsehn Can you brief more about the enhancement like where exactly we need to implement backup because I would like to work on it . :)

**Comment by timsehn** [comment]
@fulghum can point you in the right direction :-)

**Comment by PrathyushaModala** [comment]
@fulghum looking forward for your guidance :)

**Comment by fulghum** [comment]
Hey @PrathyushaModala, happy to give some more details on this... 

The `dolt backup` CLI command already supports `add` and `remove` for managing backups. This issue is to expand that support to the `dolt_backup()` stored procedure, so that the same functionality can be access from SQL. You can read more about the functionality in the [CLI documentation reference](https://docs.dolthub.com/cli-reference/cli#dolt-backup). 

After you understand the functionality, you can [check out the existing CLI implementation to see how it works](https://github.com/dolthub/dolt/blob/main/go/cmd/dolt/commands/backup.go). It will also be useful to look at [the integration tests for the `dolt backup` CLI command](https://github.com/dolthub/dolt/blob/main/integration-tests/bats/backup.bats). 

Then, you can dig into [the implementation for the `dolt_backup()` stored procedure](https://github.com/dolthub/dolt/blob/main/go/libraries/doltcore/sqle/dprocedures/dolt_backup.go) and start looking at how to apply your changes. You'll also want to dig into [the integration tests for the `dolt_backup()` stored procedure](https://github.com/dolthub/dolt/blob/main/integration-tests/bats/sql-backup.bats). 

Hope that helps you get started! Let us know how it goes and don't be shy to ask any questions.

**Comment by PrathyushaModala** [comment]
> Hey @PrathyushaModala, happy to give some more details on this...
> 
> The `dolt backup` CLI command already supports `add` and `remove` for managing backups. This issue is to expand that support to the `dolt_backup()` stored procedure, so that the same functionality can be access from SQL. You can read more about the functionality in the [CLI documentation reference](https://docs.dolthub.com/cli-reference/cli#dolt-backup).
> 
> After you understand the functionality, you can [check out the existing CLI implementation to see how it works](https://github.com/dolthub/dolt/blob/main/go/cmd/dolt/commands/backup.go). It will also be useful to look at [the integration tests for the `dolt backup` CLI command](https://github.com/dolthub/dolt/blob/main/integration-tests/bats/backup.bats).
> 
> Then, you can dig into [the implementation for the `dolt_backup()` stored procedure](https://github.com/dolthub/dolt/blob/main/go/libraries/doltcore/sqle/dprocedures/dolt_backup.go) and start looking at how to apply your changes. You'll also want to dig into [the integration tests for the `dolt_backup()` stored procedure](https://github.com/dolthub/dolt/blob/main/integration-tests/bats/sql-backup.bats).
> 
> Hope that helps you get started! Let us know how it goes and don't be shy to ask any questions.

@fulghum Thank you for the info!! Could you please assign it to me :)

**Comment by PrathyushaModala** [comment]
@fulghum , @timsehn when I tried to replicate it I'm getting this as output.
"""dolt sql-client -u root -q "call dolt_backup('add', 'test', 'file:///tmp/')"
dial tcp [::1]:3306: connectex: No connection could be made because the target machine actively refused it."""
How to reproduce the error??

**Comment by jennifersp** [comment]
This issue is fixed in https://github.com/dolthub/dolt/pull/5660
