### ISSUE TITLE
Error messages on insert can be enhanced to aid with debugging

### ISSUE THREAD

**Issue by alecstein** [dolthub/dolt#5718]
About 1/4 of time is spent debugging errors like this one:

```
An error occurred while moving data
cause: value other is not valid for this Enum
       A bad row was encountered: [48-1202402,170040,EAP,HC 70132 Crescent Cath,HCORR32720001, C1750,other,C1750,na,na,0270,MEDICAL/SURGICAL SUPPLIES AND DEVICES - GENERAL CLASSIFICATION,na,facility,inpatient,1,1,IPPrice,gross,<nil>,na,<nil>,<nil>,<nil>,21375.,FSC: 50401; BFG: 29,na,48-1201402_TheUniversityOfKansasHealthSystemKansasCityCampus_standardcharges.csv,<nil>,https://ukhspricetransparency.blob.core.windows.net/ukhs-price-transparency/48-1201402_TheUniversityOfKansasHealthSystemKansasCityCampus_standardcharges.csv,<nil>]: value other is not valid for this Enum
Errors during import can be ignored using '--continue'
```

The problem is debugging this requires manually linking row values to column names, which takes a while and is error-prone.

This would be readable if the column names were linked to the row values. I also quoted the string fields for additional clarity.
```
An error occurred while moving data
cause: value other is not valid for this Enum

A bad row was encountered **inserting into table rates**: 
hospital_tin: "48-1202402"
hospital_ccn: "170040"
code_type: "EAP"
description: "HC 70132 Crescent Cath"
procedure_code: "HCORR32720001"
code_orig: " C1750"
code_type: "other" -> **ERROR value other is not valid for this Enum**
code: "C1750"
modifier: "na"
ndc: "na"
rev_code: "0270"
rev_desc: "0270,MEDICAL/SURGICAL SUPPLIES AND DEVICES - GENERAL CLASSIFICATION"
apc: "na"
billing_class: "facility"
patient_class: "inpatient"
quantity: 1
quantity_desc: "1"
payer_desc: "IPPrice"
payer_category: "gross"
payer_name:<nil>
plan_desc: "na"
plan_id: <nil>
plan_type: <nil>
is_medicare_adv: <nil>
rate: 21375
rate_method: "FSC: 50401; BFG: 29"
rate_desc: :"na"
filename: "48-1201402_TheUniversityOfKansasHealthSystemKansasCityCampus_standardcharges.csv"
last_updated: <nil>
url: "https://ukhspricetransparency.blob.core.windows.net/ukhs-price-transparency/48-1201402_TheUniversityOfKansasHealthSystemKansasCityCampus_standardcharges.csv"
permalink: <nil>
```

**Comment by CaptainStabs** [comment]
Something like

```
something like
```
An error occurred while moving data.

Cause: The value 'other' is not valid for the 'code_meta' Enum.

A bad row was encountered:
[48-1202402, 170040, EAP, HC 70132 Crescent Cath, HCO RR32720001, C1750, other, C1750, na, na, 0270, MEDICAL/SURGICAL SUPPLIES AND DEVICES - GENERAL CLASSIFICATION, na, facility, inpatient, 1, 1, IPPrice, gross, <nil>, na, <nil>, <nil>, 21375., FSC: 50401; BFG: 29, na, 48-1201402_TheUniversityOfKansasHealthSystemKansasCityCampus_standardcharges.csv, <nil>, https://ukhspricetransparency.blob.core.windows.net/ukhs-price-transparency/48-1201402_TheUniversityOfKansasHealthSystemKansasCityCampus_standardcharges.csv, <nil>]
```
```

Would also be useful. Perhaps instead of listing *every* col in the link on a newline, only the PKs + error column are included in the output by default (with an option to include all)
