### ISSUE TITLE
Database won't start after import 

### ISSUE THREAD

**Issue by eskimo** [dolthub/dolt#5808]
After importing a ~10gb sql dump file and running `dolt sql-server` it just hangs and uses 100% of ram on a vm with 32gb.

**Comment by timsehn** [comment]
@andy-wm-arthur and @reltuk are digging into this today. We think it may be a bad interaction between chunk journal and import.

**Comment by timsehn** [comment]
So, the server did eventually start but it took 1hour.

**Comment by timsehn** [comment]
So here's a repro for what I think is a similar problem:

1. Clone this repo from dolthub: https://www.dolthub.com/repositories/dolthub/quest-v4
2. Make a dump: `dolt dump --na -fn dump.sql`. This will be 3.5GB.
3. Import that dump into a dolt database with `dolt sql dump.sql`. This will take an hour and the resulting database will be 61GB all in the chunk journal.
4. Run `dolt ls`. It takes 30s.
```
$ time dolt ls
Tables in working set:
	 code
	 file
	 insurer
	 npi_tin
	 price_metadata
	 rate
	 tin
	 tin_rate_file

dolt ls  29.73s user 7.02s system 95% cpu 38.329 total
```
6. Run `dolt gc`. Size is now 3GB.
7. Run `dolt ls` again, returns instantly.
```
$ time dolt ls
Tables in working set:
	 code
	 file
	 insurer
	 npi_tin
	 price_metadata
	 rate
	 tin
	 tin_rate_file

dolt ls  0.09s user 0.07s system 99% cpu 0.158 total
```

**Comment by fulghum** [comment]
Thanks for opening this tracking issue @eskimo. Andy found a bug that was preventing the chunk journal from being loaded correctly and causing it to be rebuilt, which is why the sql-server was taking so long to start up. I think I've seen that you picked up the new version and confirmed the fix, so I'm going to resolve this issue, but please don't hesitate to reopen if there's still an issue here and we'll hop on it.
