### ISSUE TITLE
decimal division (`/`) is slow

### ISSUE THREAD

**Issue by max-hoffman** [dolthub/dolt#5832]
The query below was executing slowly:

```sql
SELECT COUNT(id)
FROM t
WHERE width / height <=  0.236364
    OR width / height >= 6.500000;
```

schema:
```sql
CREATE TABLE t (
  id char(32) NOT NULL,
  width smallint unsigned NOT NULL,
  height smallint unsigned NOT NULL,
  PRIMARY KEY (id)
);
```

Profile:
<img width="404" alt="image" src="https://user-images.githubusercontent.com/18337807/234990815-721e6c51-7562-43db-bb87-a6907c51cab6.png">

Integer division workaround:

```sql
SELECT COUNT(id)
FROM t
WHERE (width*1000000 div height*1000000) <= 236364
    OR (width*10 div height*10) >= 65;
```

The PR that adds decimal division is here: https://github.com/dolthub/go-mysql-server/pull/1365. @zachmu said something about how this should be implemented as float-based division under the hood before returning decimal types.

**Comment by fulghum** [comment]
I've got a prototype fix in place that does the division operations with float64 types, instead of decimal.Decimal types. 

Initial perf testing looks good. On a table with 32k rows, the new implementation runs the query above in 0.10s, where as the old implementation calculates the same result in 250s. 

I still need to clean up several things and debug through any failing tests, but the fix is looking promising.

**Comment by fulghum** [comment]
Fix for this is merged into main now and will get picked up in the next release, likely in the next day or two. I'll follow up and resolve once the release is out.
