### ISSUE TITLE
CAST not fully supported

### ISSUE THREAD

**Issue by bpf120** [dolthub/dolt#5835]
``` 
mysql> SELECT CAST(10.56789 as CHAR(3));
+---------------------------+
| CAST(10.56789 as CHAR(3)) |
+---------------------------+
| 10.56789                  |
+---------------------------+
1 row in set (0.00 sec)

mysql> SELECT CAST(10 AS DECIMAL(4,2));
+--------------------------+
| CAST(10 AS DECIMAL(4,2)) |
+--------------------------+
| 10                       |
+--------------------------+
1 row in set (0.00 sec)

mysql> SELECT CAST(10.56789 AS SIGNED);
+--------------------------+
| CAST(10.56789 AS SIGNED) |
+--------------------------+
| 11                       |
+--------------------------+
1 row in set (0.00 sec)
```

SIGNED returned the expected result. CHAR and DECIMAL did not.

**Comment by fulghum** [comment]
I just pushed a PR with a fix for this. Note that our current logic that expands a Decimal value into its full digits currently only runs when a result set is sent over the wire through a SQL connection. This means that `SELECT CAST(10 AS DECIMAL(4,2))` will correctly return "10.00" from a Dolt sql-server, but will still return "10" from `dolt sql` because of how we do this type marshalling only when we convert to a SQL wire protocol. This is possible to fix of course, but it's a larger refactoring and seemed lower priority than the other fixes.

**Comment by timsehn** [comment]
Maybe close this bug and then make a new one with that much more specific issue?
