### ISSUE TITLE
Support basic functional CRSs (-1 and -2)

### ISSUE THREAD

**Issue by latot** [dolthub/dolt#5960]
Hi all, I know I have creating a lot of new issues, I'm just splitting big issues in a very smaller ones :)

I'll explain this issue from the start.

This time, in GIS we have the CRS which specifies how to interpret the coordinates of the data, lose the CRS is close to lose the data.

The CRS are a pretty big db which we can found in epsg.io

In order to do something functional, we have 2 particular/special CRS.

-1: When the CRS of the data is unknown
-2: When the CRS is not initialized

Tools like ogr2ogr/GDAL, for example looks on dbs for supported CRS,  and if not exists can try create the CRS on the db, depending on this cases it can use -1 or -2.

There is cases where we lose the CRS!, this happens in some old data, or that was mistreated, we need to store it as unknown and then update the CRS to the right one.

Should we avoid store spatial data if the db does not support the CRS, from my perspective yes, but that something that GDAL should works, I already open a issue for that.

Going back to the point, CRS -1 and -2 are very important! to keep consistent all the CRSs and workloads on the db.

I have talked with @JCOR11599 and MySQL by default does not support CRS -1 and -2!

Which is a bug and a big problem in GIS. Someone may say MySQL does not support those CRS, but would be similar for a lib to support math but not support the number 0... -1 and -2 are critical ones.

Thx!

**Comment by timsehn** [comment]
The more specific the issues, the better. Please keep them coming.

**Comment by JCOR11599** [comment]
Hey @latot, updating you here
It looks like ogr2ogr does some queries beforehand which impact the queries it generates for inserting / filling in SRIDs.
Basically, because our information_schema.st_spatial_reference_systems table didn't include an entry for SRID 3857, ogr2ogr didn't replace the SRID, and left it as `-2` aka `not initialized`.

I have a PR with a more detailed description of the issue and solution here: https://github.com/dolthub/go-mysql-server/pull/1777

It is possible for us to "support" SRID 3857 the same way we support SRID 4326, which is that it'll parse.
So you'll be able to get your data in, version it, read it, etc., but certain `st_...` functions will not work.
For reference: https://docs.dolthub.com/sql-reference/sql-support/expressions-functions-operators#functions-and-operators

**Comment by JCOR11599** [comment]
Closing in favor of: https://github.com/dolthub/dolt/issues/5988
