### ISSUE TITLE
XCA Tool shows no records when Dolt is used instead of MySQL

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#6305]
XCA is a certificate management tool:

https://hohnstaedt.de/xca/

A user substituted MySQL for Dolt. The tool worked but the records were not visible after connecting a second time. We should install and debug the issue.

```
I can connect and do everything I want to
But after connecting second time ,  no records are visible
Even though data is there
```

**Comment by fulghum** [comment]
I just tried reproducing this with the latest version of Dolt (1.7.4). In Dolt's sql-server logs, I see XCA connect to the Dolt and start creating tables, but it hits an error creating the `public_keys` table:
```sql
CREATE TABLE public_keys (item INTEGER, type CHAR(4), hash INTEGER, len INTEGER, "public" VARCHAR(8000), FOREIGN KEY (item) REFERENCES items (id))
```

When running this query manually, the error returned is:
```
ERROR 1105 (HY000): syntax error at position 91 near 'public'
```

This is due to Dolt's handling of `ANSI_QUOTES` SQL_mode. XCA is turning on the `ANSI` combination SQL mode, which includes `ANSI_QUOTES`. This allows double quotes to be used for quoting identifiers, such as the `"public"` column name in the statement above. 

After hitting that error, it rolls back the current session, so the database looks empty when we go to look in it. I tried manually creating the `public_keys` table correctly, but there are other tables/views that also don't get created. We could likely look at the created tables in a MySQL database and recreate them manually, just as another approach to find any incompatibilities faster while we figure out the right way to handle `ANSI_QUOTES` support. I'll continue poking around and seeing what we can find.

**Comment by fulghum** [comment]
I've got a prototype of `ANSI_QUOTES` support that will correctly run the query above. I still need to clean it up and add more tests, but my approach seems to be working correctly. I've got to debug another issue, but after that will switch back to this and get a PR opened.

**Comment by fulghum** [comment]
I was able to get back to testing XCA this afternoon and I found some more clues. There's a prepared insert statement to one of the tables that is erroring out, but it wasn't getting logged anywhere so it was pretty tricky to catch – I eventually found it in a wire capture. 

When a `ComPrepare` command comes in, the code we use from vitess dispatches to our command handler, but before it does that, it tries to parse the statement to look for parameter place holders in the statement. Unfortunately, that lowest layer of the code doesn't know that we're in `ANSI_QUOTES` sql_mode, so it just tries to parse the statement, errors out on the ANSI quotes it sees and sends back an error packet before the query is ever sent to our processing code in go-mysql-server. 

I've got a couple of ideas on how we can get this working correctly and will experiment with a couple tomorrow.

**Comment by fulghum** [comment]
Another quick update... after hacking around the sql_mode parsing issue in the vitess layer, XCA is now working correctly with Dolt. I tested creating private keys and certificates, then restarting XCA and reconnecting to the remote database, and verified that the previous data showed up correctly in the app. 

I've still got a good bit of cleanup and testing for this prototype before I open a PR for the fix, but it's awesome to see XCA working with Dolt now!
