### ISSUE TITLE
Querying dolt_diff_table errors out when table column has shrunk

### ISSUE THREAD

**Issue by ricardoreiter** [dolthub/dolt#6391]
- Table A with Column Y varchar(300).
- Make a commit inserting a string in Column Y that is > 100 long.
- Make a different commit changing that row text to a < 100 long string and changing the column size to varchar(100)
- Query select * from dolt_diff_tableA errors out

**Comment by timsehn** [comment]
We'll get on this today. Either @zachmu or @fulghum

**Comment by fulghum** [comment]
Good find @ricardoreiter. I've got a repro and am running it through the debugger now.

**Comment by fulghum** [comment]
I played with a few options for this and I think I've got a good solution. We are constrained by the `dolt_diff_<tablename>`'s schema of course – every row in `dolt_diff_<tablename>` has to conform to that schema, even though the rows may have come from older table versions with different schemas. If the types are widened (e.g. `varchar(10)` → `varchar(100)`) then there's no problem putting older values into them, but going the other direction can cause this error where we can't fit an old value into the new type. 

To fix this, I'm promoting each type in the diff table's schema to the largest possible type in the same family (e.g. `varchar(10)` → `text`). There are still some more edge cases here around even larger type changes (e.g. changing a `geometry` column to an `int` column), but we'll leave those for another day and focus on the issue you're hitting.

I'm going to clean up my prototype and add some more tests, then I'll get the fix out for review.

**Comment by fulghum** [comment]
@ricardoreiter Thank you for reporting this one! I just merged in the fix I described above. It didn't get in in time to go out with the 1.8.5 release earlier today, but it's queued up to go out in the next release, likely tomorrow. Don't hesitate to let us know if you'd like to test the fix out today and I'll be happy to fast track a release for you.

**Comment by fulghum** [comment]
Hey @ricardoreiter – heads up that the type changes in this PR were a little more impactful than we had intended. We decided to revisit this solution and instead of auto-promoting all column types to their largest settings, we now log a SQL warning in the session when a historical value being displayed in a `dolt_diff_<tablename>` system table won't fit in the current schema. This is consistent with how we treat non-coercible type changes (e.g. when changing a column from something like `geometry` to `float`, there's no option to coerce the old value into the new type) and definitely still better than the old behavior where only an error was returned and no result set.
