### ISSUE TITLE
Connect to a managed doltlab instance remote from local dolt repository

### ISSUE THREAD

**Issue by rilor2** [dolthub/dolt#6429]
I installed doltlab on a VM running in the cloud, i have dolt installed locally on a docker container. 

I'm trying to connect the login from my local instance to the remote on the VM. I didn't create any new user so the default user has name `admin` and email `no-reply@fake.host`. 

I set up the same values on my local configuration for `dolt config --get user.name` and `dolt config --get user.email`. 

Despite that, whenever i try to `dolt login` to doltlab on my VM, i'm asked to add a new credential key on doltlab, and, after adding the credential, it seems like the `login` command is stuck and cannot retrieve the correct association from doltlab:
```
Please associate your key with your account.
Checking remote server looking for key association.
requesting update.. 
```

do i need to add any other configuration in order to manage to login and use doltlab on the VM as remote host?

**Comment by coffeegoddd** [comment]
@rilor2 can you share the `dolt login` command you ran?

I installed dolt on a Docker container and ran following the docs [here](https://docs.dolthub.com/products/doltlab/administrator#auth-dolt-client):

```
dolt login --insecure --auth-endpoint doltlab.dolthub.com:50051 --login-url http://doltlab.dolthub.com/settings/credentials
```

This points at the DoltLab instance we have running at `doltlab.dolthub.com`. After doing so, I see the message that dolt is trying to open a browser to `http://doltlab.dolthub.com/settings/credentials#<pub key>`, but can't since it's in the container, so I navigate to that endpoint myself (I'm logged in as `admin` as well), add the new credential on the settings page, and after doing so see the `dolt login` command succeed with:

```
Key successfully associated with user: admin email dustin@dolthub.com
```

Alternatively, you can avoid the `dolt login` command all together by running:
```
dolt creds new
Credentials created successfully.
pub key: <public key>
```

Then adding that to the credentials page of your DoltLab instance. After that, your dolt client should be authenticated against the remote.

**Comment by rilor2** [comment]
The port 50051 was not open, and that was the issue indeed. The issue can be closed. Thanks
