### ISSUE TITLE
`dolt_patch()` table function should consider filters for schema or data only changes

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolt#6446]
If I use the `dolt_patch` table function and filter for schema only changes (like `SELECT * FROM DOLT_PATCH('WORKING', 'main', 'items') WHERE diff_type = 'schema'`) the performance is bad for diffs with a lot of data changes. It should consider the schema-only filter and only get schema changes

**Comment by max-hoffman** [comment]
Table functions are generator nodes (`ExecSourceRel`) with different interfaces than regular tables. Table functions only implement a `RowIter`, and do not have interfaces for declaring indexes and constructing index lookups.

The way a system table, for example, absorbs a WHERE filter (ex: `select * from dolt_diff_mytable where to_commit = 'HEAD' and from_commit = 'HEAD~') is by declaring an index on the target filter expressions. Because system tables implement the other table interfaces, the analyzer will generate `IndexedTableAccess` that the system table can choose to implement as it pleases.

Table functions could behave similarly, but their interface is so different that several changes are required to create the same indexing effect.

One strategy would push table functions into the `IndexAddressableTable` interface (or something similar that `generateIndexScans` can match). Table functions would just need to implement this, expose indexes aligning with the indexable fields, and then GMS would do the rest.

We are pretty close to changing how GMS generates index scans, and this might be an opportunity to put more of the logical complexity into GMS rather than the table function interface. After the filter pushdown rule, indexable filters will be the parent node of table functions. We could just add a rule that matches `FILTER->TABLE_FUNC` and an interface that lets table functions accept filters/indexes. Standalone indexes clash with join indexes, so join costing would need to be aware and overriding the default index for table functions used in special join operators. This whole setup is a good starting place for absorbing how we do all index generation at a later point.
