### ISSUE TITLE
Drop Database is destructive. Could make it more safe.

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#6484]
We had an issue where an operator accidentally dropped a database. It was recovered from a clone but for our product this is the only truly destructive SQL command. We should explore options to make it safer.

One option floated is to move the database to a different location and only delete it for real on `dolt gc` or `call dolt_gc()`. 

We could also have a dolt restore command that shows databases in this state and gives the option to recreate them.

Open to other options here.

**Comment by nicktobey** [comment]
Is there a compelling reason to delete it at all? If none of our other SQL commands are destructive, why should this one be? To save space? There are lots of SQL commands that reduce space on MySQL but not on Dolt because we store a versioned history. I don't see why this should be any different.

I suggest that "dropped" is just another state that the working set can be in. If users want to recover it, it's as simple as `use`ing a previous commit. If they want delete it for good, they can delete it from disk manually (we could maybe provide a stored procedure, but I think that permanently destroying the database *should* be hard.)

**Comment by timsehn** [comment]
The issue with the above approach is that the target of versioning in the application is a table. There is a lot of product chrome required to uplevel that to a namespace of tables (a database). It doable but it requires a lot more design than moving it instead of `rm`-ing the directory and only deleting that directory on a `dolt gc`.
