### ISSUE TITLE
Slow merge when new index was added (re-indexing every merge?)

### ISSUE THREAD

**Issue by algotr34** [dolthub/dolt#6951]
I try to use the database https://www.dolthub.com/repositories/post-no-preference/stocks table ohlcv, but it doesn't have an index only on the stock itself, so i created a new branch and created a new index... but now every time that i do pull to master & merge to the branch, the merge takes a lot of time, like it is re-building the index from the start instead of just adding only the updated data. anyone have any idea how to solve it and have an additional index on an existing database, but not having to re-index it every time? is it solvable at all in dolt?

dolt version 1.24.1

**Comment by fulghum** [comment]
Hi @algotr34, thanks for taking the time to report this one! 🙏 

I was able to repro the issue, and your intuition is correct – that new index that only exists on the destination side of the merge is getting completely rebuilt at the end of the merge. Before that code runs, the index **does** get updated with the merged data, so that rebuild is not necessary. The current code sees that the index doesn't exist in the ancestor or on the other side of the merge, so it decides to rebuild it. That doesn't seem necessary, and I believe that check is just leftover from before we supported updating secondary indexes during merges. 

I've got a change in my workspace that stops rebuilding the index in this case and when I test it with my repro for this issue, the merge of new data into the branch with the index takes less than 1s (instead of ~2m). 

I'm going to poke around a bit more and make sure there aren't legitimate cases where we really do need to rebuild a secondary index in this condition, but I believe this is the correct fix. I'll update again once I get a PR out for review and we'll try to get this fix out quickly for you. Thanks for helping us find this one!

**Comment by fulghum** [comment]
The fix for this issue has been released in [Dolt 1.24.2](https://github.com/dolthub/dolt/releases/tag/v1.24.2).

Thanks for taking the time to report this so we could fix it! 🙏 Let us know if you hit any other snags with Dolt and we'll be happy to help.
