### ISSUE TITLE
Unexpected Results when Using IN after Creating Index

### ISSUE THREAD

**Issue by suyZhong** [dolthub/dolt#7155]
Considering the test case below:

```sql
CREATE TABLE t0(c0 INT);
INSERT INTO t0 (c0) VALUES (0);
CREATE INDEX i0 ON t0(c0 );

SELECT * FROM t0; -- 0
SELECT (t0.c0 IN ((100000/100000000))) FROM t0; -- 1
SELECT * FROM  t0 WHERE (t0.c0 IN ((100000/100000000)));
-- Expected: 0
-- Actual:   Empty
```

The third `SELECT` returns an empty result, which is surprising: If the result of second query is `1`, the value of the `IN` expression should be `1`, and thus the third query should return the row in `t0`.

I originally find this by building dolt from source version https://github.com/dolthub/dolt/commit/d7678ab58494ce8c52bb951702fd2f9608727119. Could also reproduce on 1.29.4

----
Sorry, I suppose it is the second query that should be unexpected.

**Comment by JCOR11599** [comment]
This issue is related to https://github.com/dolthub/dolt/issues/7098
It appears that the div operator is returning the wrong decimal type (has scale 0), leading to bad conversions inside the `IN` operator.
I suspect other boolean conditions relying on comparing ints to decimals (that come from dividing two ints) will have a similar problem.

A simpler repro:
```sql
select 0 in (1/1000); -- should be 0 
```
