### ISSUE TITLE
Increasing Code Cov and integration zero-code tool for tests

### ISSUE THREAD

**Issue by Sonichigo** [dolthub/dolt#7343]
I was going through the codebase and pr, to see how ways to contribute. I noticed that there is a folder for integration tests. I use a tool called Keploy to for testing and data mocks, I can use it for some test to get code coverage (will try to get at least 70% before making pr) ? Can i contribute in this way?

Reference: - 
1. https://github.com/dolthub/dolt/tree/main/integration-tests
2. https://github.com/keploy/keploy

**Comment by fulghum** [comment]
Hey @Sonichigo, thank you for reaching out! If you're looking for ways to contribute, our preference would be tackling some bugs in the issue queue, particularly [those labeled with "good first issue"](https://github.com/dolthub/dolt/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).

Keploy looks like an interesting tool, but I don't think it's a great fit for the Dolt project, based on what I read in the docs. It looks like it's targeted more at backend development, with features such as mocking. I could see how those features would be useful for a backend system with many dependencies. Dolt is a single binary that customers can download and run on their own machines, and we generally prefer our integration testing to use real external dependencies (where we have them) instead of mocks. Thanks for taking the time to let us know about Keploy though, we'll keep it in mind for backend work.
