### ISSUE TITLE
dolt should look for .dolt directory in descending directory tree

### ISSUE THREAD

**Issue by michelk** [dolthub/dolt#742]
git searches for `.git` directory in the descending directory tree. It would be nice, if dolt would behave in the same way. 

e.g.
## git
```bash
git init
mkdir test
cd test
git status
```
Output: 

    On branch master
    
    No commits yet

## dolt
```bash
dolt init
mkdir test
cd test
dolt status
```
Output: 

    The current directory is not a valid dolt repository.
    run: dolt init before trying to run this command

Tested with `dolt version 0.17.2`

**Comment by zachmu** [comment]
Good catch, Michel. We are working on correcting this discrepancy.

**Comment by timsehn** [comment]
This is not as simple as Zach is making it out to be and we are discussing internally. 

Dolt does not understand directories. When you `dolt init` a directory, it creates a `.dolt` directory where all your data lives. There are two special files that we version right now in that directory called `LICENSE.md` and `README.md`. We may eventually want to allow people to version a filesystem tree along with their Dolt repository. At that point, Dolt will "understand directories".

All that said, our bias is to match git so we'll try to do that.

**Comment by michelk** [comment]
I thought, it would be enough to add a command-line argument (e.g. `--dolt-dir`, similar to `--git-dir`). And if it is omitted, search for a `.dolt` directory in the descending directory tree, starting in the current working directory.

**Comment by zachmu** [comment]
It's been a while since we commented here, but I think we've decided to not implement this behavior. Unlike git, there's not a clear answer to the question of whether a directory inside the top-level directory is "part of" a dolt repository. So we're going to leave this alone to make the answer more explicit: only the top-level dolt directory counts as part of the repository, and any subdirectories aren't part of it.
