### ISSUE TITLE
Got "Invalid ON UPDATE clause" after bump to v0.18.0

### ISSUE THREAD

**Issue by kom0055** [dolthub/dolt#7555]
DDL like this
```
CREATE TABLE d_log 
(
    id              bigint unsigned NOT NULL AUTO_INCREMENT,  
    created_at      datetime(6)  DEFAULT CURRENT_TIMESTAMP(6),  
    updated_at      datetime(6)  DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(6),  
    PRIMARY KEY (id)  
) ENGINE = InnoDB  
  DEFAULT CHARSET = utf8mb4  
  COLLATE = utf8mb4_general_ci;  
```

**Comment by fulghum** [comment]
Thanks for reporting this one @kom0055. 

In older versions of GMS/Dolt, we parsed the `ON UPDATE` clause, but didn't actually use it. Back in December, we added support for handling them (https://github.com/dolthub/go-mysql-server/pull/2188), but we don't currently support the precision argument in `CURRENT_TIMESTAMP(6)`. 

If you need a quick workaround, I confirmed that the dropping the `6` argument from `CURRENT_TIMESTAMP(6)` does execute correctly with Dolt, so the GMS behavior should also work with that. 

@jycor is looking at the fix for accepting the precision argument today for you and we'll keep you updated on the progress. Thank you for helping us find this gap with MySQL compatibility! 🙏

**Comment by bpf120** [comment]
@kom0055 , thanks for notifying us. We'd love to learn about your Dolt use case too. If you want to share, you can [email me](mailto:brianf@dolthub.com) or swing by our [Discord](https://discord.gg/gqr7K4VNKe).

**Comment by jycor** [comment]
Hey @kom0055, thanks for catching my mistake.
The fix for this has been merged to GMS main.

**Comment by kom0055** [comment]
> Hey @kom0055, thanks for catching my mistake. The fix for this has been merged to GMS main.

good job buddy, could you plz release new verson of GMS, thx ?

**Comment by kom0055** [comment]
> @kom0055 , thanks for notifying us. We'd love to learn about your Dolt use case too. If you want to share, you can [email me](mailto:brianf@dolthub.com) or swing by our [Discord](https://discord.gg/gqr7K4VNKe).

use GMS in unit tests, good imlementation
