### ISSUE TITLE
Migrate `dolt remote` to SQL

### ISSUE THREAD

**Issue by macneale4** [dolthub/dolt#7622]
`dotl remote` currently bypasses a running sql-server, and should instead use the `DOLT_REMOTE()` stored procedure.

Difficulty: Low
Value: Medium

Overarching Ticket: https://github.com/dolthub/dolt/issues/3922

**Comment by macneale4** [comment]
User tripped on this: https://github.com/dolthub/dolt/issues/7548

**Comment by fulghum** [comment]
A customer requested the ability to use the cloud provider params for the `dolt_remote()` stored procedure. We support these on the command line through `dolt remote`, but not in the stored procedure. 

Bumping this issue, since as part of migrating to the SQL interface, we'd need to cover those options in the stored procedure.
