### ISSUE TITLE
`dolt diff --stat -r json` produces invalid JSON

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt#7800]
`dolt diff --stats -r json` produces invalid JSON (schema_diff has invalid content`):
```
$ dolt diff b6u0b8g9crutgpaummtla6rbft91o2ue --stat -r json 
{"tables":[{"name":"cbp_apprehensions_monthly","schema_diff":[prev size: 29676, new size: 29676, adds: 0, deletes: 0, modifications: 24990
4,686 Rows Unmodified (15.79%)
0 Rows Added (0.00%)
0 Rows Deleted (0.00%)
24,990 Rows Modified (84.21%)
0 Cells Added (0.00%)
0 Cells Deleted (0.00%)
49,980 Cells Modified (24.06%)
(29,676 Row Entries vs 29,676 Row Entries)

}]}
```

**Comment by nicktobey** [comment]
`dolt diff -r sql --stat` also produces invalid SQL.

Honestly, `dolt diff --stat` is essentially a different command than `dolt diff`, since it doesn't actually produce a diff, only diff stats. We could define a json encoding of the diff stats, or we could just make `--stat` and `-r` mutually exclusive.

@timsehn, you labelled this as a customer issue? Does the customer want the diff stats in JSON format, or are we just looking to avoid generating invalid JSON output here?
