### ISSUE TITLE
Unknown push Error When Pushing Large DB to Remote

### ISSUE THREAD

**Issue by farhanhubble** [dolthub/dolt#8156]
**Description**

I have a large DB in doltlab with 2 million rows in the largest table. I am able to clone, pull and push to the repo. However when I try to push the data to another repo I get this error:
```log
stats bootstrap aborted because myDB exceeds the default row limit; manually run "ANALYZE <table>" or "call dolt_stats_restart()" to collect statistics
unknown push error; failed to get all chunks.
```
Here are the table stats. The DB size on disk is around 100GB.
  | TABLE_NAME | TABLE_ROWS
-- | -- | --
  | a| 1987342
  | b| 664316
  | c| 644757
  | d| 474438
  | e| 449252
  | f| 252134
  | g| 201262
  | h| 201262
  | i| 201262
  | j| 201262
  | k| 201262
  | l| 3917

**Reproduction**
- `dolt clone url/A --branch main --depth 1`
- `dolt remote add alt_origin url/B`
- `dolt push alt_origin main`

**Additional Information**
```csv
dolt version: 1.42.4
```

**Comment by timsehn** [comment]
I think this is the result of trying to push a partial clone. Error message could be better. @macneale4 can look.

**Comment by macneale4** [comment]
Yes, pushing a shallow clone is not supported. The error you're seeing in nonsensical though. Will fix.

**Comment by macneale4** [comment]
FWIW, I'm not seeing the same error you are. The error I see is: 

`- Uploading...unknown push error; failed to get all chunks.`

Which is also not a very descriptive error and I'll fix it.

That said, I'm not sure if the fix I have in flight will address your specific bug since I can't reproduce it exactly. Are there other commands in play that you are doing? The stats/analyze code is a little surprising to me to be happening in the context of a push.
