### ISSUE TITLE
Scheduled events fail to execute after a server restart

### ISSUE THREAD

**Issue by coffeegoddd** [dolthub/dolt#8167]
Tracking issue for behavior observed where scheduled events seem to be disabled by a server restart.

**Comment by fulghum** [comment]
After an event has been executed it can get marked as `DISABLED` erroneously. The event persistence code in Dolt incorrectly assumes that the event is not on the `main` branch (the only branch where events are enabled), so it marks the event as disabled. This doesn't affect the event scheduler, since it has a copy of the enabled event in memory, but when the server is restarted, the event doesn't get scheduled again, because of it's disabled state.
