### ISSUE TITLE
Connector/NET: A warning causes stack overflow

### ISSUE THREAD

**Issue by tkovacs-dev** [dolthub/dolt#8440]
If the statement you execute issues a warning (like division by zero, or running DROP DATABASE IF EXISTS nonexistent_db) a stack overflow error occurs in the Connector/NET code.

How to reproduce:
- start dolt (1.43.3) with `dolt sql-server`
- run this code with .net 8.0, MySql.Data version 9.0.0 (or 8.0.33):
```
using MySql.Data.MySqlClient;

public static class DoltTest
{
    public static void Main()
    {
        using var conn = new MySqlConnection("server=127.0.0.1;port=3306;sslmode=none;user=root;password=;CharSet=utf8;database=dolt-db");
        conn.Open();
        MySqlHelper.ExecuteScalar(conn, "select 1/0");
    }
}
```

**Comment by timsehn** [comment]
Thanks for the issue. @jycor or @fulghum (our .net expert) will look at this today.

**Comment by fulghum** [comment]
Hi @tkovacs-dev, thanks for reporting this issue to us. I've been able to repro this behavior and look at the wire logs. This appears to happen because Dolt is not clearing the session warnings after a call to `SHOW WARNINGS`. From the wire logs, I can see that the .NET app is calling `SHOW WARNINGS` many hundreds of times, until it overflows its stack. 

From a SQL shell connected to Dolt, you can see that when we call `SHOW WARNINGS` after your example query, a warning is still being reported, so the .NET framework keeps calling `SHOW WARNINGS` over and over until it pops its stack. 

```sql
mysql> select 1/0;
+-----+
| 1/0 |
+-----+
| NULL |
+-----+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+---------------+
| Level   | Code | Message       |
+---------+------+---------------+
| Warning | 1365 | Division by 0 |
+---------+------+---------------+
1 row in set, 1 warning (0.01 sec)

mysql> show warnings;
+---------+------+---------------+
| Level   | Code | Message       |
+---------+------+---------------+
| Warning | 1365 | Division by 0 |
+---------+------+---------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+---------------+
| Level   | Code | Message       |
+---------+------+---------------+
| Warning | 1365 | Division by 0 |
+---------+------+---------------+
1 row in set, 1 warning (0.01 sec)
```

That warning isn't getting properly cleared from the call to `SHOW WARNINGS`. We'll keep digging in and see what's going wrong.

**Comment by fulghum** [comment]
We dug into this some more and figured out what's going on. Our logic that manages clearing sessions warnings runs at the end of analysis, but these types of warnings only happen during the execution/evaluation phase, which is after analysis. That causes the warning status to be slightly out of sync and to not get cleared correctly until two statements have been executed successfully – they should be cleared on the first statement that is executed successfully. 

@jycor is going to take it from here to look at refactoring that logic in the analyzer.

**Comment by jycor** [comment]
Hey @tkovacs-dev, thanks for reporting this issue.
The fix for this has been merged to dolt main, and a release will be coming out shortly.

Let us know if it works for you!

**Comment by tkovacs-dev** [comment]
@jycor Works great, thank you!
